package com.ksource.liangfa.domain;

import java.util.Date;

public class CaseModifiedExpLog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.LOG_ID
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	private Long logId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.OPERATOR
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	private String operator;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_TIME
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	private Date expTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.INSERT_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	private Integer insertCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.UPDATE_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	private Integer updateCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.DELETE_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	private Integer deleteCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_FILE
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	private String expFile;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.LOG_ID
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.LOG_ID
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public Long getLogId() {
		return logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.LOG_ID
	 * @param logId  the value for LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.LOG_ID
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public void setLogId(Long logId) {
		this.logId = logId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.OPERATOR
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.OPERATOR
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public String getOperator() {
		return operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.OPERATOR
	 * @param operator  the value for LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.OPERATOR
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public void setOperator(String operator) {
		this.operator = operator;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_TIME
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_TIME
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public Date getExpTime() {
		return expTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_TIME
	 * @param expTime  the value for LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_TIME
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public void setExpTime(Date expTime) {
		this.expTime = expTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.INSERT_COUNT
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.INSERT_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public Integer getInsertCount() {
		return insertCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.INSERT_COUNT
	 * @param insertCount  the value for LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.INSERT_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public void setInsertCount(Integer insertCount) {
		this.insertCount = insertCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.UPDATE_COUNT
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.UPDATE_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public Integer getUpdateCount() {
		return updateCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.UPDATE_COUNT
	 * @param updateCount  the value for LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.UPDATE_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public void setUpdateCount(Integer updateCount) {
		this.updateCount = updateCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.DELETE_COUNT
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.DELETE_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public Integer getDeleteCount() {
		return deleteCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.DELETE_COUNT
	 * @param deleteCount  the value for LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.DELETE_COUNT
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public void setDeleteCount(Integer deleteCount) {
		this.deleteCount = deleteCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_FILE
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_FILE
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public String getExpFile() {
		return expFile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_FILE
	 * @param expFile  the value for LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG.EXP_FILE
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	public void setExpFile(String expFile) {
		this.expFile = expFile;
	}

	private String operatorName;
	private Date startExpTime;
	private Date endExpTime;
	private String orgCode;
	private String orgName;

	public String getOperatorName() {
		return operatorName;
	}

	public void setOperatorName(String operatorName) {
		this.operatorName = operatorName;
	}

	public Date getStartExpTime() {
		return startExpTime;
	}

	public void setStartExpTime(Date startExpTime) {
		this.startExpTime = startExpTime;
	}

	public Date getEndExpTime() {
		return endExpTime;
	}

	public void setEndExpTime(Date endExpTime) {
		this.endExpTime = endExpTime;
	}

	public String getOrgCode() {
		return orgCode;
	}

	public void setOrgCode(String orgCode) {
		this.orgCode = orgCode;
	}

	public String getOrgName() {
		return orgName;
	}

	public void setOrgName(String orgName) {
		this.orgName = orgName;
	}
}