package com.ksource.liangfa.domain;

import java.util.Date;
import java.math.BigDecimal;

public class CaseImport {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_ID
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Integer importId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Date importTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NO
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String caseNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NAME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String caseName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUTER
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String inputer;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Date inputTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_UNIT
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String inputUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_STATE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String caseState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.RECORD_SRC
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String recordSrc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.LATEST_POCESS_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Date latestPocessTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.PROC_KEY
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String procKey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TYPE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Integer inputType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.VERSION_NO
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Integer versionNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_ASSIGN
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Integer isAssign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Date anfaTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_ADDRESS
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String anfaAddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_SUSPECTED_CRIMINAL
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Integer isSuspectedCriminal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_TYPE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Integer caseType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.AMOUNT_INVOLVED
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Double amountInvolved;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_SUGGEST
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String undertakerSuggest;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_REASON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String caseReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String undertaker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Date undertakerTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UPLOAD_FLAG
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private Integer uploadFlag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_DETAIL_NAME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String caseDetailName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_PARTY_JSON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String casePartyJson;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_COMPANY_JSON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	private String caseCompanyJson;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_ID
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_ID
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Integer getImportId() {
		return importId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_ID
	 * @param importId  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_ID
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setImportId(Integer importId) {
		this.importId = importId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_TIME
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Date getImportTime() {
		return importTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_TIME
	 * @param importTime  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.IMPORT_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setImportTime(Date importTime) {
		this.importTime = importTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NO
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NO
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getCaseNo() {
		return caseNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NO
	 * @param caseNo  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NO
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCaseNo(String caseNo) {
		this.caseNo = caseNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NAME
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NAME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getCaseName() {
		return caseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NAME
	 * @param caseName  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_NAME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUTER
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUTER
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getInputer() {
		return inputer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUTER
	 * @param inputer  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUTER
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setInputer(String inputer) {
		this.inputer = inputer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TIME
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Date getInputTime() {
		return inputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TIME
	 * @param inputTime  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_UNIT
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_UNIT
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getInputUnit() {
		return inputUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_UNIT
	 * @param inputUnit  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_UNIT
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setInputUnit(String inputUnit) {
		this.inputUnit = inputUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_STATE
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_STATE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getCaseState() {
		return caseState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_STATE
	 * @param caseState  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_STATE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCaseState(String caseState) {
		this.caseState = caseState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.RECORD_SRC
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.RECORD_SRC
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getRecordSrc() {
		return recordSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.RECORD_SRC
	 * @param recordSrc  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.RECORD_SRC
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setRecordSrc(String recordSrc) {
		this.recordSrc = recordSrc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.LATEST_POCESS_TIME
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.LATEST_POCESS_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Date getLatestPocessTime() {
		return latestPocessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.LATEST_POCESS_TIME
	 * @param latestPocessTime  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.LATEST_POCESS_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setLatestPocessTime(Date latestPocessTime) {
		this.latestPocessTime = latestPocessTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.PROC_KEY
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.PROC_KEY
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getProcKey() {
		return procKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.PROC_KEY
	 * @param procKey  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.PROC_KEY
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setProcKey(String procKey) {
		this.procKey = procKey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TYPE
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TYPE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Integer getInputType() {
		return inputType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TYPE
	 * @param inputType  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.INPUT_TYPE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setInputType(Integer inputType) {
		this.inputType = inputType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.VERSION_NO
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.VERSION_NO
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Integer getVersionNo() {
		return versionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.VERSION_NO
	 * @param versionNo  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.VERSION_NO
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setVersionNo(Integer versionNo) {
		this.versionNo = versionNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_ASSIGN
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_ASSIGN
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Integer getIsAssign() {
		return isAssign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_ASSIGN
	 * @param isAssign  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_ASSIGN
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setIsAssign(Integer isAssign) {
		this.isAssign = isAssign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_TIME
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Date getAnfaTime() {
		return anfaTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_TIME
	 * @param anfaTime  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setAnfaTime(Date anfaTime) {
		this.anfaTime = anfaTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_ADDRESS
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_ADDRESS
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getAnfaAddress() {
		return anfaAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_ADDRESS
	 * @param anfaAddress  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.ANFA_ADDRESS
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setAnfaAddress(String anfaAddress) {
		this.anfaAddress = anfaAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_SUSPECTED_CRIMINAL
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_SUSPECTED_CRIMINAL
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Integer getIsSuspectedCriminal() {
		return isSuspectedCriminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_SUSPECTED_CRIMINAL
	 * @param isSuspectedCriminal  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.IS_SUSPECTED_CRIMINAL
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setIsSuspectedCriminal(Integer isSuspectedCriminal) {
		this.isSuspectedCriminal = isSuspectedCriminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_TYPE
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_TYPE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Integer getCaseType() {
		return caseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_TYPE
	 * @param caseType  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_TYPE
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCaseType(Integer caseType) {
		this.caseType = caseType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.AMOUNT_INVOLVED
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.AMOUNT_INVOLVED
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Double getAmountInvolved() {
		return amountInvolved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.AMOUNT_INVOLVED
	 * @param amountInvolved  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.AMOUNT_INVOLVED
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setAmountInvolved(Double amountInvolved) {
		this.amountInvolved = amountInvolved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_SUGGEST
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_SUGGEST
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getUndertakerSuggest() {
		return undertakerSuggest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_SUGGEST
	 * @param undertakerSuggest  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_SUGGEST
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setUndertakerSuggest(String undertakerSuggest) {
		this.undertakerSuggest = undertakerSuggest;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_REASON
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_REASON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getCaseReason() {
		return caseReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_REASON
	 * @param caseReason  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_REASON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCaseReason(String caseReason) {
		this.caseReason = caseReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getUndertaker() {
		return undertaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER
	 * @param undertaker  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setUndertaker(String undertaker) {
		this.undertaker = undertaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_TIME
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Date getUndertakerTime() {
		return undertakerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_TIME
	 * @param undertakerTime  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.UNDERTAKER_TIME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setUndertakerTime(Date undertakerTime) {
		this.undertakerTime = undertakerTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UPLOAD_FLAG
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.UPLOAD_FLAG
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public Integer getUploadFlag() {
		return uploadFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.UPLOAD_FLAG
	 * @param uploadFlag  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.UPLOAD_FLAG
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setUploadFlag(Integer uploadFlag) {
		this.uploadFlag = uploadFlag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_DETAIL_NAME
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_DETAIL_NAME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getCaseDetailName() {
		return caseDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_DETAIL_NAME
	 * @param caseDetailName  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_DETAIL_NAME
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCaseDetailName(String caseDetailName) {
		this.caseDetailName = caseDetailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_PARTY_JSON
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_PARTY_JSON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getCasePartyJson() {
		return casePartyJson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_PARTY_JSON
	 * @param casePartyJson  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_PARTY_JSON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCasePartyJson(String casePartyJson) {
		this.casePartyJson = casePartyJson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_COMPANY_JSON
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_COMPANY_JSON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public String getCaseCompanyJson() {
		return caseCompanyJson;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_COMPANY_JSON
	 * @param caseCompanyJson  the value for LIANGFA_XINXIANG20170222.CASE_IMPORT.CASE_COMPANY_JSON
	 * @mbggenerated  Tue Apr 04 12:40:07 CST 2017
	 */
	public void setCaseCompanyJson(String caseCompanyJson) {
		this.caseCompanyJson = caseCompanyJson;
	}

	private Date startImportTime;
    private Date endImportTime;


    public Date getStartImportTime() {
        return startImportTime;
    }

    public void setStartImportTime(Date startImportTime) {
        this.startImportTime = startImportTime;
    }

    public Date getEndImportTime() {
        return endImportTime;
    }

    public void setEndImportTime(Date endImportTime) {
        this.endImportTime = endImportTime;
    }
    /*private Integer attaCount;

    public Integer getAttaCount() {
        return attaCount;
    }

    public void setAttaCount(Integer attaCount) {
        this.attaCount = attaCount;
    }
    
    private String goodsInvolved;//涉案物品名称
    private String goodsDisposeResult;//涉案物品处理情况
    private String goodsCount;//涉案物品数量

    private String partyDisposeResult;//当事人处理情况的结果


	public String getGoodsInvolved() {
		return goodsInvolved;
	}

	public void setGoodsInvolved(String goodsInvolved) {
		this.goodsInvolved = goodsInvolved;
	}

	public String getGoodsDisposeResult() {
		return goodsDisposeResult;
	}

	public void setGoodsDisposeResult(String goodsDisposeResult) {
		this.goodsDisposeResult = goodsDisposeResult;
	}

	public String getGoodsCount() {
		return goodsCount;
	}

	public void setGoodsCount(String goodsCount) {
		this.goodsCount = goodsCount;
	}

	public String getPartyDisposeResult() {
		return partyDisposeResult;
	}

	public void setPartyDisposeResult(String partyDisposeResult) {
		this.partyDisposeResult = partyDisposeResult;
	}
    
	private Integer isLowerLimitMoney;//是否低于行政处罚下限金额
	private Integer isExecution;//是否申请法院强制执行 1 0
	private Integer noYiSongState;//未达标准不移送公安状态2
	private Integer isDqdj;//是否为打侵打假冒类型

	public Integer getIsLowerLimitMoney() {
		return isLowerLimitMoney;
	}
	public void setIsLowerLimitMoney(Integer isLowerLimitMoney) {
		this.isLowerLimitMoney = isLowerLimitMoney;
	}

	public Integer getIsExecution() {
		return isExecution;
	}

	public void setIsExecution(Integer isExecution) {
		this.isExecution = isExecution;
	}

	public Integer getNoYiSongState() {
		return noYiSongState;
	}

	public void setNoYiSongState(Integer noYiSongState) {
		this.noYiSongState = noYiSongState;
	}

	public Integer getIsDqdj() {
		return isDqdj;
	}

	public void setIsDqdj(Integer isDqdj) {
		this.isDqdj = isDqdj;
	}
	
	private Double amountInvolvedChufa;//处罚时涉案金额统计
	private String firstUnit;//初始受案行政执法机关

	public Double getAmountInvolvedChufa() {
		return amountInvolvedChufa;
	}

	public void setAmountInvolvedChufa(Double amountInvolvedChufa) {
		this.amountInvolvedChufa = amountInvolvedChufa;
	}

	public String getFirstUnit() {
		return firstUnit;
	}

	public void setFirstUnit(String firstUnit) {
		this.firstUnit = firstUnit;
	}
	
	private Integer identifyType;//鉴定类别
	private String identifyOrg;//鉴定机构
	private String identifyPerson;//鉴定的身份
	private Date identifyTime;//鉴定时间
	private String identifyResult;//鉴定意见主要内容
	
	public Integer getIdentifyType() {
		return identifyType;
	}


	public void setIdentifyType(Integer identifyType) {
		this.identifyType = identifyType;
	}

	public String getIdentifyOrg() {
		return identifyOrg;
	}

	public void setIdentifyOrg(String identifyOrg) {
		this.identifyOrg = identifyOrg;
	}

	public String getIdentifyPerson() {
		return identifyPerson;
	}

	public void setIdentifyPerson(String identifyPerson) {
		this.identifyPerson = identifyPerson;
	}

	public Date getIdentifyTime() {
		return identifyTime;
	}

	public void setIdentifyTime(Date identifyTime) {
		this.identifyTime = identifyTime;
	}

	public String getIdentifyResult() {
		return identifyResult;
	}

	public void setIdentifyResult(String identifyResult) {
		this.identifyResult = identifyResult;
	}
	
	private String courtName;//强制执行法院名称
	private Integer dqdjType;//打侵打假类型
	private String dqdjTypeName;
	
	
	public String getDqdjTypeName() {
		return dqdjTypeName;
	}

	public void setDqdjTypeName(String dqdjTypeName) {
		this.dqdjTypeName = dqdjTypeName;
	}

	public String getCourtName() {
		return courtName;
	}

	public void setCourtName(String courtName) {
		this.courtName = courtName;
	}

	public Integer getDqdjType() {
		return dqdjType;
	}

	public void setDqdjType(Integer dqdjType) {
		this.dqdjType = dqdjType;
	}
	
	private String illegalSituationName;
	private String illegalSituationId;//违法情形id


	public String getIllegalSituationName() {
		return illegalSituationName;
	}

	public void setIllegalSituationName(String illegalSituationName) {
		this.illegalSituationName = illegalSituationName;
	}

	public String getIllegalSituationId() {
		return illegalSituationId;
	}

	public void setIllegalSituationId(String illegalSituationId) {
		this.illegalSituationId = illegalSituationId;
	}*/
	
	private String anfaAddressName;


	public String getAnfaAddressName() {
		return anfaAddressName;
	}

	public void setAnfaAddressName(String anfaAddressName) {
		this.anfaAddressName = anfaAddressName;
	}
	
	
}