package com.ksource.liangfa.domain;

public class CaseSequence {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.SEQUENCE_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    private Long sequenceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.CASE_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    private String caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.PROC_KEY
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    private String procKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.FLOW_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    private String flowId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.SEQUENCE_ID
     *
     * @return the value of LIANGFA_XINXIANG20170421.CASE_SEQUENCE.SEQUENCE_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public Long getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.SEQUENCE_ID
     *
     * @param sequenceId the value for LIANGFA_XINXIANG20170421.CASE_SEQUENCE.SEQUENCE_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public void setSequenceId(Long sequenceId) {
        this.sequenceId = sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.CASE_ID
     *
     * @return the value of LIANGFA_XINXIANG20170421.CASE_SEQUENCE.CASE_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public String getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.CASE_ID
     *
     * @param caseId the value for LIANGFA_XINXIANG20170421.CASE_SEQUENCE.CASE_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public void setCaseId(String caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.PROC_KEY
     *
     * @return the value of LIANGFA_XINXIANG20170421.CASE_SEQUENCE.PROC_KEY
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public String getProcKey() {
        return procKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.PROC_KEY
     *
     * @param procKey the value for LIANGFA_XINXIANG20170421.CASE_SEQUENCE.PROC_KEY
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public void setProcKey(String procKey) {
        this.procKey = procKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.FLOW_ID
     *
     * @return the value of LIANGFA_XINXIANG20170421.CASE_SEQUENCE.FLOW_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public String getFlowId() {
        return flowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170421.CASE_SEQUENCE.FLOW_ID
     *
     * @param flowId the value for LIANGFA_XINXIANG20170421.CASE_SEQUENCE.FLOW_ID
     *
     * @mbggenerated Wed Apr 26 09:08:05 CST 2017
     */
    public void setFlowId(String flowId) {
        this.flowId = flowId;
    }
}