package com.ksource.liangfa.domain;

public class CaseAccuseKey {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.ACCUSE_ID
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	private Integer accuseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.CASE_ID
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.ZM_TYPE
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	private Integer zmType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.ACCUSE_ID
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_ACCUSE.ACCUSE_ID
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	public Integer getAccuseId() {
		return accuseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.ACCUSE_ID
	 * @param accuseId  the value for LIANGFA_XINXIANG20170222.CASE_ACCUSE.ACCUSE_ID
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	public void setAccuseId(Integer accuseId) {
		this.accuseId = accuseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.CASE_ID
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_ACCUSE.CASE_ID
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.CASE_ID
	 * @param caseId  the value for LIANGFA_XINXIANG20170222.CASE_ACCUSE.CASE_ID
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.ZM_TYPE
	 * @return  the value of LIANGFA_XINXIANG20170222.CASE_ACCUSE.ZM_TYPE
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	public Integer getZmType() {
		return zmType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170222.CASE_ACCUSE.ZM_TYPE
	 * @param zmType  the value for LIANGFA_XINXIANG20170222.CASE_ACCUSE.ZM_TYPE
	 * @mbggenerated  Tue Mar 28 15:16:34 CST 2017
	 */
	public void setZmType(Integer zmType) {
		this.zmType = zmType;
	}
}