package com.ksource.liangfa.domain;

import java.util.Date;

public class CaseFenpai {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.CASE_ID
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_ORG
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	private Integer fenpaiOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.JIESHOU_ORG
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	private Integer jieshouOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_TIME
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	private Date fenpaiTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.UNDERTAKER
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	private String undertaker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_REASON
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	private String fenpaiReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FILE_ID
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	private String fileId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.CASE_ID
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_FENPAI.CASE_ID
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.CASE_ID
	 * @param caseId  the value for LIANGFA_XINXIANG20170424.CASE_FENPAI.CASE_ID
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_ORG
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_ORG
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public Integer getFenpaiOrg() {
		return fenpaiOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_ORG
	 * @param fenpaiOrg  the value for LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_ORG
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public void setFenpaiOrg(Integer fenpaiOrg) {
		this.fenpaiOrg = fenpaiOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.JIESHOU_ORG
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_FENPAI.JIESHOU_ORG
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public Integer getJieshouOrg() {
		return jieshouOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.JIESHOU_ORG
	 * @param jieshouOrg  the value for LIANGFA_XINXIANG20170424.CASE_FENPAI.JIESHOU_ORG
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public void setJieshouOrg(Integer jieshouOrg) {
		this.jieshouOrg = jieshouOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_TIME
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_TIME
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public Date getFenpaiTime() {
		return fenpaiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_TIME
	 * @param fenpaiTime  the value for LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_TIME
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public void setFenpaiTime(Date fenpaiTime) {
		this.fenpaiTime = fenpaiTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.UNDERTAKER
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_FENPAI.UNDERTAKER
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public String getUndertaker() {
		return undertaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.UNDERTAKER
	 * @param undertaker  the value for LIANGFA_XINXIANG20170424.CASE_FENPAI.UNDERTAKER
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public void setUndertaker(String undertaker) {
		this.undertaker = undertaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_REASON
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_REASON
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public String getFenpaiReason() {
		return fenpaiReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_REASON
	 * @param fenpaiReason  the value for LIANGFA_XINXIANG20170424.CASE_FENPAI.FENPAI_REASON
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public void setFenpaiReason(String fenpaiReason) {
		this.fenpaiReason = fenpaiReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FILE_ID
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_FENPAI.FILE_ID
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_FENPAI.FILE_ID
	 * @param fileId  the value for LIANGFA_XINXIANG20170424.CASE_FENPAI.FILE_ID
	 * @mbggenerated  Thu Jul 27 17:22:05 CST 2017
	 */
	public void setFileId(String fileId) {
		this.fileId = fileId;
	}
	
	//分派单位名称
	private String fenpaiOrgName;
	//接收单位
	private String jieshouOrgName;

	public String getFenpaiOrgName() {
		return fenpaiOrgName;
	}

	public void setFenpaiOrgName(String fenpaiOrgName) {
		this.fenpaiOrgName = fenpaiOrgName;
	}

	public String getJieshouOrgName() {
		return jieshouOrgName;
	}

	public void setJieshouOrgName(String jieshouOrgName) {
		this.jieshouOrgName = jieshouOrgName;
	}
	
	//分派材料附件名称
	private String fileName;
	//办理人
	private String transactPerson;
	//办理时间
	private Date transactTime;

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getTransactPerson() {
		return transactPerson;
	}

	public void setTransactPerson(String transactPerson) {
		this.transactPerson = transactPerson;
	}

	public Date getTransactTime() {
		return transactTime;
	}

	public void setTransactTime(Date transactTime) {
		this.transactTime = transactTime;
	}
	
}