package com.ksource.liangfa.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CaseRequireLianExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public CaseRequireLianExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("ID like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("ID not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andRequireTimeIsNull() {
            addCriterion("REQUIRE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andRequireTimeIsNotNull() {
            addCriterion("REQUIRE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andRequireTimeEqualTo(Date value) {
            addCriterion("REQUIRE_TIME =", value, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeNotEqualTo(Date value) {
            addCriterion("REQUIRE_TIME <>", value, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeGreaterThan(Date value) {
            addCriterion("REQUIRE_TIME >", value, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("REQUIRE_TIME >=", value, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeLessThan(Date value) {
            addCriterion("REQUIRE_TIME <", value, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeLessThanOrEqualTo(Date value) {
            addCriterion("REQUIRE_TIME <=", value, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeIn(List<Date> values) {
            addCriterion("REQUIRE_TIME in", values, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeNotIn(List<Date> values) {
            addCriterion("REQUIRE_TIME not in", values, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeBetween(Date value1, Date value2) {
            addCriterion("REQUIRE_TIME between", value1, value2, "requireTime");
            return (Criteria) this;
        }

        public Criteria andRequireTimeNotBetween(Date value1, Date value2) {
            addCriterion("REQUIRE_TIME not between", value1, value2, "requireTime");
            return (Criteria) this;
        }

        public Criteria andAttachFileIsNull() {
            addCriterion("ATTACH_FILE is null");
            return (Criteria) this;
        }

        public Criteria andAttachFileIsNotNull() {
            addCriterion("ATTACH_FILE is not null");
            return (Criteria) this;
        }

        public Criteria andAttachFileEqualTo(String value) {
            addCriterion("ATTACH_FILE =", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileNotEqualTo(String value) {
            addCriterion("ATTACH_FILE <>", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileGreaterThan(String value) {
            addCriterion("ATTACH_FILE >", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileGreaterThanOrEqualTo(String value) {
            addCriterion("ATTACH_FILE >=", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileLessThan(String value) {
            addCriterion("ATTACH_FILE <", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileLessThanOrEqualTo(String value) {
            addCriterion("ATTACH_FILE <=", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileLike(String value) {
            addCriterion("ATTACH_FILE like", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileNotLike(String value) {
            addCriterion("ATTACH_FILE not like", value, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileIn(List<String> values) {
            addCriterion("ATTACH_FILE in", values, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileNotIn(List<String> values) {
            addCriterion("ATTACH_FILE not in", values, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileBetween(String value1, String value2) {
            addCriterion("ATTACH_FILE between", value1, value2, "attachFile");
            return (Criteria) this;
        }

        public Criteria andAttachFileNotBetween(String value1, String value2) {
            addCriterion("ATTACH_FILE not between", value1, value2, "attachFile");
            return (Criteria) this;
        }

        public Criteria andUndertakerIsNull() {
            addCriterion("UNDERTAKER is null");
            return (Criteria) this;
        }

        public Criteria andUndertakerIsNotNull() {
            addCriterion("UNDERTAKER is not null");
            return (Criteria) this;
        }

        public Criteria andUndertakerEqualTo(String value) {
            addCriterion("UNDERTAKER =", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerNotEqualTo(String value) {
            addCriterion("UNDERTAKER <>", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerGreaterThan(String value) {
            addCriterion("UNDERTAKER >", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerGreaterThanOrEqualTo(String value) {
            addCriterion("UNDERTAKER >=", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerLessThan(String value) {
            addCriterion("UNDERTAKER <", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerLessThanOrEqualTo(String value) {
            addCriterion("UNDERTAKER <=", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerLike(String value) {
            addCriterion("UNDERTAKER like", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerNotLike(String value) {
            addCriterion("UNDERTAKER not like", value, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerIn(List<String> values) {
            addCriterion("UNDERTAKER in", values, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerNotIn(List<String> values) {
            addCriterion("UNDERTAKER not in", values, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerBetween(String value1, String value2) {
            addCriterion("UNDERTAKER between", value1, value2, "undertaker");
            return (Criteria) this;
        }

        public Criteria andUndertakerNotBetween(String value1, String value2) {
            addCriterion("UNDERTAKER not between", value1, value2, "undertaker");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("MEMO is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("MEMO is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("MEMO =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("MEMO <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("MEMO >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("MEMO >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("MEMO <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("MEMO <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("MEMO in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("MEMO not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("MEMO between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("MEMO not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNull() {
            addCriterion("CASE_ID is null");
            return (Criteria) this;
        }

        public Criteria andCaseIdIsNotNull() {
            addCriterion("CASE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCaseIdEqualTo(String value) {
            addCriterion("CASE_ID =", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotEqualTo(String value) {
            addCriterion("CASE_ID <>", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThan(String value) {
            addCriterion("CASE_ID >", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
            addCriterion("CASE_ID >=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThan(String value) {
            addCriterion("CASE_ID <", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLessThanOrEqualTo(String value) {
            addCriterion("CASE_ID <=", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdLike(String value) {
            addCriterion("CASE_ID like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotLike(String value) {
            addCriterion("CASE_ID not like", value, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdIn(List<String> values) {
            addCriterion("CASE_ID in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotIn(List<String> values) {
            addCriterion("CASE_ID not in", values, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdBetween(String value1, String value2) {
            addCriterion("CASE_ID between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCaseIdNotBetween(String value1, String value2) {
            addCriterion("CASE_ID not between", value1, value2, "caseId");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("CREATE_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("CREATE_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("CREATE_TIME =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("CREATE_TIME <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("CREATE_TIME >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("CREATE_TIME <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_TIME <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("CREATE_TIME in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("CREATE_TIME not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_TIME not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("CREATE_USER is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("CREATE_USER is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("CREATE_USER =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("CREATE_USER <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("CREATE_USER >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("CREATE_USER <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("CREATE_USER like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("CREATE_USER not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("CREATE_USER in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("CREATE_USER not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("CREATE_USER between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNull() {
            addCriterion("CREATE_USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIsNotNull() {
            addCriterion("CREATE_USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameEqualTo(String value) {
            addCriterion("CREATE_USER_NAME =", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotEqualTo(String value) {
            addCriterion("CREATE_USER_NAME <>", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThan(String value) {
            addCriterion("CREATE_USER_NAME >", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_NAME >=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThan(String value) {
            addCriterion("CREATE_USER_NAME <", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_NAME <=", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameLike(String value) {
            addCriterion("CREATE_USER_NAME like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotLike(String value) {
            addCriterion("CREATE_USER_NAME not like", value, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameIn(List<String> values) {
            addCriterion("CREATE_USER_NAME in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotIn(List<String> values) {
            addCriterion("CREATE_USER_NAME not in", values, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameBetween(String value1, String value2) {
            addCriterion("CREATE_USER_NAME between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateUserNameNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_NAME not between", value1, value2, "createUserName");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIsNull() {
            addCriterion("CREATE_ORG is null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIsNotNull() {
            addCriterion("CREATE_ORG is not null");
            return (Criteria) this;
        }

        public Criteria andCreateOrgEqualTo(String value) {
            addCriterion("CREATE_ORG =", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNotEqualTo(String value) {
            addCriterion("CREATE_ORG <>", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgGreaterThan(String value) {
            addCriterion("CREATE_ORG >", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_ORG >=", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgLessThan(String value) {
            addCriterion("CREATE_ORG <", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgLessThanOrEqualTo(String value) {
            addCriterion("CREATE_ORG <=", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgLike(String value) {
            addCriterion("CREATE_ORG like", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNotLike(String value) {
            addCriterion("CREATE_ORG not like", value, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgIn(List<String> values) {
            addCriterion("CREATE_ORG in", values, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNotIn(List<String> values) {
            addCriterion("CREATE_ORG not in", values, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgBetween(String value1, String value2) {
            addCriterion("CREATE_ORG between", value1, value2, "createOrg");
            return (Criteria) this;
        }

        public Criteria andCreateOrgNotBetween(String value1, String value2) {
            addCriterion("CREATE_ORG not between", value1, value2, "createOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgIsNull() {
            addCriterion("RECEIVE_ORG is null");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgIsNotNull() {
            addCriterion("RECEIVE_ORG is not null");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgEqualTo(String value) {
            addCriterion("RECEIVE_ORG =", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgNotEqualTo(String value) {
            addCriterion("RECEIVE_ORG <>", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgGreaterThan(String value) {
            addCriterion("RECEIVE_ORG >", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgGreaterThanOrEqualTo(String value) {
            addCriterion("RECEIVE_ORG >=", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgLessThan(String value) {
            addCriterion("RECEIVE_ORG <", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgLessThanOrEqualTo(String value) {
            addCriterion("RECEIVE_ORG <=", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgLike(String value) {
            addCriterion("RECEIVE_ORG like", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgNotLike(String value) {
            addCriterion("RECEIVE_ORG not like", value, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgIn(List<String> values) {
            addCriterion("RECEIVE_ORG in", values, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgNotIn(List<String> values) {
            addCriterion("RECEIVE_ORG not in", values, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgBetween(String value1, String value2) {
            addCriterion("RECEIVE_ORG between", value1, value2, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andReceiveOrgNotBetween(String value1, String value2) {
            addCriterion("RECEIVE_ORG not between", value1, value2, "receiveOrg");
            return (Criteria) this;
        }

        public Criteria andFileExplainIsNull() {
            addCriterion("FILE_EXPLAIN is null");
            return (Criteria) this;
        }

        public Criteria andFileExplainIsNotNull() {
            addCriterion("FILE_EXPLAIN is not null");
            return (Criteria) this;
        }

        public Criteria andFileExplainEqualTo(String value) {
            addCriterion("FILE_EXPLAIN =", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainNotEqualTo(String value) {
            addCriterion("FILE_EXPLAIN <>", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainGreaterThan(String value) {
            addCriterion("FILE_EXPLAIN >", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainGreaterThanOrEqualTo(String value) {
            addCriterion("FILE_EXPLAIN >=", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainLessThan(String value) {
            addCriterion("FILE_EXPLAIN <", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainLessThanOrEqualTo(String value) {
            addCriterion("FILE_EXPLAIN <=", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainLike(String value) {
            addCriterion("FILE_EXPLAIN like", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainNotLike(String value) {
            addCriterion("FILE_EXPLAIN not like", value, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainIn(List<String> values) {
            addCriterion("FILE_EXPLAIN in", values, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainNotIn(List<String> values) {
            addCriterion("FILE_EXPLAIN not in", values, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainBetween(String value1, String value2) {
            addCriterion("FILE_EXPLAIN between", value1, value2, "fileExplain");
            return (Criteria) this;
        }

        public Criteria andFileExplainNotBetween(String value1, String value2) {
            addCriterion("FILE_EXPLAIN not between", value1, value2, "fileExplain");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated do_not_delete_during_merge Thu Jan 25 10:43:49 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table CASE_REQUIRE_LIAN
     *
     * @mbg.generated Thu Jan 25 10:43:49 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}