package com.ksource.liangfa.domain;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

public class CaseTurnover {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.CASE_ID
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private String caseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_ORG
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private Integer yisongOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.JIESHOU_ORG
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private Integer jieshouOrg;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_TIME
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private Date yisongTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_REASON
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private String yisongReason;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.MEMO
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.FILE_ID
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private String fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.UNDERTAKER
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	private String undertaker;


	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.CASE_ID
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.CASE_ID
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public String getCaseId() {
		return caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.CASE_ID
	 * @param caseId  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.CASE_ID
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setCaseId(String caseId) {
		this.caseId = caseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_ORG
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_ORG
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public Integer getYisongOrg() {
		return yisongOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_ORG
	 * @param yisongOrg  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_ORG
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setYisongOrg(Integer yisongOrg) {
		this.yisongOrg = yisongOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.JIESHOU_ORG
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.JIESHOU_ORG
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public Integer getJieshouOrg() {
		return jieshouOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.JIESHOU_ORG
	 * @param jieshouOrg  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.JIESHOU_ORG
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setJieshouOrg(Integer jieshouOrg) {
		this.jieshouOrg = jieshouOrg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_TIME
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_TIME
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public Date getYisongTime() {
		return yisongTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_TIME
	 * @param yisongTime  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_TIME
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setYisongTime(Date yisongTime) {
		this.yisongTime = yisongTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_REASON
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_REASON
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public String getYisongReason() {
		return yisongReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_REASON
	 * @param yisongReason  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.YISONG_REASON
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setYisongReason(String yisongReason) {
		this.yisongReason = yisongReason;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.MEMO
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.MEMO
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.MEMO
	 * @param memo  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.MEMO
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.FILE_ID
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.FILE_ID
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public String getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.FILE_ID
	 * @param fileId  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.FILE_ID
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setFileId(String fileId) {
		this.fileId = fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.UNDERTAKER
	 * @return  the value of LIANGFA_XINXIANG20170424.CASE_TURNOVER.UNDERTAKER
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public String getUndertaker() {
		return undertaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.CASE_TURNOVER.UNDERTAKER
	 * @param undertaker  the value for LIANGFA_XINXIANG20170424.CASE_TURNOVER.UNDERTAKER
	 * @mbggenerated  Thu Jul 27 17:38:08 CST 2017
	 */
	public void setUndertaker(String undertaker) {
		this.undertaker = undertaker;
	}

	//==========================================================================
    /**移�?�管辖前的案件id*/
    private String oldCaseId;
  	private String caseName;
  	private String caseNo;
  	/**案件录入机构名称*/
  	private String createOrgName;
  	private Date inputTime;
  	private String caseState;
  	private Double amountInvolved;
  	/**模糊查询�?始时�?*/
  	private Date startTime;
  	private Date endTime;
  	/** 预警信息集合
	 * 
	 * key�? warnCaseparty、warnCaseCompany、orgAmount、beyondAmount
	 *  
	 *  */
	private Map<String,Object> warnMap = new HashMap<String, Object>();
	
	
	public String getOldCaseId() {
		return oldCaseId;
	}

	public void setOldCaseId(String oldCaseId) {
		this.oldCaseId = oldCaseId;
	}

	public String getCaseName() {
		return caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	public String getCaseNo() {
		return caseNo;
	}

	public void setCaseNo(String caseNo) {
		this.caseNo = caseNo;
	}

	public String getCreateOrgName() {
		return createOrgName;
	}

	public void setCreateOrgName(String createOrgName) {
		this.createOrgName = createOrgName;
	}

	public Date getInputTime() {
		return inputTime;
	}

	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	public String getCaseState() {
		return caseState;
	}

	public void setCaseState(String caseState) {
		this.caseState = caseState;
	}

	public Double getAmountInvolved() {
		return amountInvolved;
	}

	public void setAmountInvolved(Double amountInvolved) {
		this.amountInvolved = amountInvolved;
	}

	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	public Map<String, Object> getWarnMap() {
		return warnMap;
	}

	public void setWarnMap(Map<String, Object> warnMap) {
		this.warnMap = warnMap;
	}
  	
	//移送单位名称
	private String yisongOrgName;
	//接收单位名称
	private String jieshouOrgName;


	public String getYisongOrgName() {
		return yisongOrgName;
	}

	public void setYisongOrgName(String yisongOrgName) {
		this.yisongOrgName = yisongOrgName;
	}

	public String getJieshouOrgName() {
		return jieshouOrgName;
	}

	public void setJieshouOrgName(String jieshouOrgName) {
		this.jieshouOrgName = jieshouOrgName;
	}
	
	//附件名称
	private String fileName;
	//办理人
	private String transactPerson;
	//办理时间
	private Date transactTime;

	public String getFileName() {
		return fileName;
	}

	public void setFileName(String fileName) {
		this.fileName = fileName;
	}

	public String getTransactPerson() {
		return transactPerson;
	}

	public void setTransactPerson(String transactPerson) {
		this.transactPerson = transactPerson;
	}

	public Date getTransactTime() {
		return transactTime;
	}

	public void setTransactTime(Date transactTime) {
		this.transactTime = transactTime;
	}
	
}