package com.ksource.liangfa.domain;

import java.util.Date;

public class CaseFilter {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.FILTER_ID
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer filterId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.ORG_CODE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer orgCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_AMOUNT_INVOLVED
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Double minAmountInvolved;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_AMOUNT_INVOLVED
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Double maxAmountInvolved;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_CASE_INPUT_TIME
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Date minCaseInputTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_CASE_INPUT_TIME
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Date maxCaseInputTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_SERIOUS_CASE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer isSeriousCase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_DISCUSS_CASE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer isDiscussCase;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.CHUFA_TIMES
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer chufaTimes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_BEYOND_EIGHTY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer isBeyondEighty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_LOWER_LIMIT_MONEY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer isLowerLimitMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_IDENTIFY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	private Integer isIdentify;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.FILTER_ID
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.FILTER_ID
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getFilterId() {
		return filterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.FILTER_ID
	 * @param filterId  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.FILTER_ID
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setFilterId(Integer filterId) {
		this.filterId = filterId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.ORG_CODE
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.ORG_CODE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getOrgCode() {
		return orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.ORG_CODE
	 * @param orgCode  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.ORG_CODE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setOrgCode(Integer orgCode) {
		this.orgCode = orgCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_AMOUNT_INVOLVED
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_AMOUNT_INVOLVED
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Double getMinAmountInvolved() {
		return minAmountInvolved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_AMOUNT_INVOLVED
	 * @param minAmountInvolved  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_AMOUNT_INVOLVED
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setMinAmountInvolved(Double minAmountInvolved) {
		this.minAmountInvolved = minAmountInvolved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_AMOUNT_INVOLVED
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_AMOUNT_INVOLVED
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Double getMaxAmountInvolved() {
		return maxAmountInvolved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_AMOUNT_INVOLVED
	 * @param maxAmountInvolved  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_AMOUNT_INVOLVED
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setMaxAmountInvolved(Double maxAmountInvolved) {
		this.maxAmountInvolved = maxAmountInvolved;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_CASE_INPUT_TIME
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_CASE_INPUT_TIME
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Date getMinCaseInputTime() {
		return minCaseInputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_CASE_INPUT_TIME
	 * @param minCaseInputTime  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MIN_CASE_INPUT_TIME
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setMinCaseInputTime(Date minCaseInputTime) {
		this.minCaseInputTime = minCaseInputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_CASE_INPUT_TIME
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_CASE_INPUT_TIME
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Date getMaxCaseInputTime() {
		return maxCaseInputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_CASE_INPUT_TIME
	 * @param maxCaseInputTime  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.MAX_CASE_INPUT_TIME
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setMaxCaseInputTime(Date maxCaseInputTime) {
		this.maxCaseInputTime = maxCaseInputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_SERIOUS_CASE
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_SERIOUS_CASE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getIsSeriousCase() {
		return isSeriousCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_SERIOUS_CASE
	 * @param isSeriousCase  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_SERIOUS_CASE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setIsSeriousCase(Integer isSeriousCase) {
		this.isSeriousCase = isSeriousCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_DISCUSS_CASE
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_DISCUSS_CASE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getIsDiscussCase() {
		return isDiscussCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_DISCUSS_CASE
	 * @param isDiscussCase  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_DISCUSS_CASE
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setIsDiscussCase(Integer isDiscussCase) {
		this.isDiscussCase = isDiscussCase;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.CHUFA_TIMES
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.CHUFA_TIMES
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getChufaTimes() {
		return chufaTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.CHUFA_TIMES
	 * @param chufaTimes  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.CHUFA_TIMES
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setChufaTimes(Integer chufaTimes) {
		this.chufaTimes = chufaTimes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_BEYOND_EIGHTY
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_BEYOND_EIGHTY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getIsBeyondEighty() {
		return isBeyondEighty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_BEYOND_EIGHTY
	 * @param isBeyondEighty  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_BEYOND_EIGHTY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setIsBeyondEighty(Integer isBeyondEighty) {
		this.isBeyondEighty = isBeyondEighty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_LOWER_LIMIT_MONEY
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_LOWER_LIMIT_MONEY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getIsLowerLimitMoney() {
		return isLowerLimitMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_LOWER_LIMIT_MONEY
	 * @param isLowerLimitMoney  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_LOWER_LIMIT_MONEY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setIsLowerLimitMoney(Integer isLowerLimitMoney) {
		this.isLowerLimitMoney = isLowerLimitMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_IDENTIFY
	 * @return  the value of LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_IDENTIFY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public Integer getIsIdentify() {
		return isIdentify;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_IDENTIFY
	 * @param isIdentify  the value for LIANGFA_HUBEI_V2_XIAN.CASE_FILTER.IS_IDENTIFY
	 * @mbggenerated  Tue Mar 15 11:40:12 CST 2016
	 */
	public void setIsIdentify(Integer isIdentify) {
		this.isIdentify = isIdentify;
	}

	//案件编号
    private String caseNo;
    //案件名称
    private String caseName;
    
  //录入单位
    private Integer orgId;
    
  //案件状态
    private String caseState;
    
    //罪名ID
    private String accuseId; 
    
    //行政区划
    private Integer districtId;
    
    
    /** 录入单位 */
    private Integer inputerOrgCode;
    
    //组织机构orgPath
    private String orgPath;
    
	public Integer getInputerOrgCode() {
		return inputerOrgCode;
	}

	public void setInputerOrgCode(Integer inputerOrgCode) {
		this.inputerOrgCode = inputerOrgCode;
	}

	public Integer getOrgId() {
		return orgId;
	}

	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	public String getCaseState() {
		return caseState;
	}

	public void setCaseState(String caseState) {
		this.caseState = caseState;
	}

	public String getCaseNo() {
		return caseNo;
	}

	public void setCaseNo(String caseNo) {
		this.caseNo = caseNo;
	}

	public String getCaseName() {
		return caseName;
	}

	public void setCaseName(String caseName) {
		this.caseName = caseName;
	}

	public String getAccuseId() {
		return accuseId;
	}

	public void setAccuseId(String accuseId) {
		this.accuseId = accuseId;
	}

	public Integer getDistrictId() {
		return districtId;
	}

	public void setDistrictId(Integer districtId) {
		this.districtId = districtId;
	}

	public String getOrgPath() {
		return orgPath;
	}

	public void setOrgPath(String orgPath) {
		this.orgPath = orgPath;
	}
	
}