package com.ksource.liangfa.domain;

import java.util.Date;

import com.ksource.common.log.businesslog.ModelCode;
import com.ksource.common.log.businesslog.ModelName;

public class CommunionReceive {
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ID
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private Integer receiveId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.COMMUNION_ID
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private Integer communionId;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.TITLE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private String title;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_ORG
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private Integer sendOrg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_TIME
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private Date sendTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ORG
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private String receiveOrg;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_STATUS
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private Integer readStatus;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_TIME
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private Date readTime;
    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.CONTENT
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ID
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ID
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public Integer getReceiveId() {
        return receiveId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ID
     * @param receiveId  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ID
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setReceiveId(Integer receiveId) {
        this.receiveId = receiveId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.COMMUNION_ID
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.COMMUNION_ID
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public Integer getCommunionId() {
        return communionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.COMMUNION_ID
     * @param communionId  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.COMMUNION_ID
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setCommunionId(Integer communionId) {
        this.communionId = communionId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.TITLE
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.TITLE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.TITLE
     * @param title  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.TITLE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_ORG
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_ORG
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public Integer getSendOrg() {
        return sendOrg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_ORG
     * @param sendOrg  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_ORG
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setSendOrg(Integer sendOrg) {
        this.sendOrg = sendOrg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_TIME
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_TIME
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_TIME
     * @param sendTime  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.SEND_TIME
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ORG
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ORG
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public String getReceiveOrg() {
        return receiveOrg;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ORG
     * @param receiveOrg  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.RECEIVE_ORG
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setReceiveOrg(String receiveOrg) {
        this.receiveOrg = receiveOrg;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_STATUS
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_STATUS
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public Integer getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_STATUS
     * @param readStatus  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_STATUS
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setReadStatus(Integer readStatus) {
        this.readStatus = readStatus;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_TIME
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_TIME
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public Date getReadTime() {
        return readTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_TIME
     * @param readTime  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.READ_TIME
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setReadTime(Date readTime) {
        this.readTime = readTime;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.CONTENT
     * @return  the value of LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.CONTENT
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.CONTENT
     * @param content  the value for LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE.CONTENT
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /** 发�?�单位名�? */
    private String sendOrgName;

    public String getSendOrgName() {
		return sendOrgName;
	}

	public void setSendOrgName(String sendOrgName) {
		this.sendOrgName = sendOrgName;
	}
}