package com.ksource.liangfa.domain;

import java.util.ArrayList;
import java.util.List;

public class DictionaryExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public DictionaryExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andDtCodeIsNull() {
			addCriterion("DT_CODE is null");
			return (Criteria) this;
		}

		public Criteria andDtCodeIsNotNull() {
			addCriterion("DT_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andDtCodeEqualTo(String value) {
			addCriterion("DT_CODE =", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeNotEqualTo(String value) {
			addCriterion("DT_CODE <>", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeGreaterThan(String value) {
			addCriterion("DT_CODE >", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeGreaterThanOrEqualTo(String value) {
			addCriterion("DT_CODE >=", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeLessThan(String value) {
			addCriterion("DT_CODE <", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeLessThanOrEqualTo(String value) {
			addCriterion("DT_CODE <=", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeLike(String value) {
			addCriterion("DT_CODE like", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeNotLike(String value) {
			addCriterion("DT_CODE not like", value, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeIn(List<String> values) {
			addCriterion("DT_CODE in", values, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeNotIn(List<String> values) {
			addCriterion("DT_CODE not in", values, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeBetween(String value1, String value2) {
			addCriterion("DT_CODE between", value1, value2, "dtCode");
			return (Criteria) this;
		}

		public Criteria andDtCodeNotBetween(String value1, String value2) {
			addCriterion("DT_CODE not between", value1, value2, "dtCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeIsNull() {
			addCriterion("GROUP_CODE is null");
			return (Criteria) this;
		}

		public Criteria andGroupCodeIsNotNull() {
			addCriterion("GROUP_CODE is not null");
			return (Criteria) this;
		}

		public Criteria andGroupCodeEqualTo(String value) {
			addCriterion("GROUP_CODE =", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeNotEqualTo(String value) {
			addCriterion("GROUP_CODE <>", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeGreaterThan(String value) {
			addCriterion("GROUP_CODE >", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeGreaterThanOrEqualTo(String value) {
			addCriterion("GROUP_CODE >=", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeLessThan(String value) {
			addCriterion("GROUP_CODE <", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeLessThanOrEqualTo(String value) {
			addCriterion("GROUP_CODE <=", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeLike(String value) {
			addCriterion("GROUP_CODE like", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeNotLike(String value) {
			addCriterion("GROUP_CODE not like", value, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeIn(List<String> values) {
			addCriterion("GROUP_CODE in", values, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeNotIn(List<String> values) {
			addCriterion("GROUP_CODE not in", values, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeBetween(String value1, String value2) {
			addCriterion("GROUP_CODE between", value1, value2, "groupCode");
			return (Criteria) this;
		}

		public Criteria andGroupCodeNotBetween(String value1, String value2) {
			addCriterion("GROUP_CODE not between", value1, value2, "groupCode");
			return (Criteria) this;
		}

		public Criteria andDtNameIsNull() {
			addCriterion("DT_NAME is null");
			return (Criteria) this;
		}

		public Criteria andDtNameIsNotNull() {
			addCriterion("DT_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andDtNameEqualTo(String value) {
			addCriterion("DT_NAME =", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameNotEqualTo(String value) {
			addCriterion("DT_NAME <>", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameGreaterThan(String value) {
			addCriterion("DT_NAME >", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameGreaterThanOrEqualTo(String value) {
			addCriterion("DT_NAME >=", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameLessThan(String value) {
			addCriterion("DT_NAME <", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameLessThanOrEqualTo(String value) {
			addCriterion("DT_NAME <=", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameLike(String value) {
			addCriterion("DT_NAME like", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameNotLike(String value) {
			addCriterion("DT_NAME not like", value, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameIn(List<String> values) {
			addCriterion("DT_NAME in", values, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameNotIn(List<String> values) {
			addCriterion("DT_NAME not in", values, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameBetween(String value1, String value2) {
			addCriterion("DT_NAME between", value1, value2, "dtName");
			return (Criteria) this;
		}

		public Criteria andDtNameNotBetween(String value1, String value2) {
			addCriterion("DT_NAME not between", value1, value2, "dtName");
			return (Criteria) this;
		}

		public Criteria andActiveIsNull() {
			addCriterion("ACTIVE is null");
			return (Criteria) this;
		}

		public Criteria andActiveIsNotNull() {
			addCriterion("ACTIVE is not null");
			return (Criteria) this;
		}

		public Criteria andActiveEqualTo(Integer value) {
			addCriterion("ACTIVE =", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotEqualTo(Integer value) {
			addCriterion("ACTIVE <>", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThan(Integer value) {
			addCriterion("ACTIVE >", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveGreaterThanOrEqualTo(Integer value) {
			addCriterion("ACTIVE >=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThan(Integer value) {
			addCriterion("ACTIVE <", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveLessThanOrEqualTo(Integer value) {
			addCriterion("ACTIVE <=", value, "active");
			return (Criteria) this;
		}

		public Criteria andActiveIn(List<Integer> values) {
			addCriterion("ACTIVE in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotIn(List<Integer> values) {
			addCriterion("ACTIVE not in", values, "active");
			return (Criteria) this;
		}

		public Criteria andActiveBetween(Integer value1, Integer value2) {
			addCriterion("ACTIVE between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andActiveNotBetween(Integer value1, Integer value2) {
			addCriterion("ACTIVE not between", value1, value2, "active");
			return (Criteria) this;
		}

		public Criteria andSerialIsNull() {
			addCriterion("SERIAL is null");
			return (Criteria) this;
		}

		public Criteria andSerialIsNotNull() {
			addCriterion("SERIAL is not null");
			return (Criteria) this;
		}

		public Criteria andSerialEqualTo(Integer value) {
			addCriterion("SERIAL =", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialNotEqualTo(Integer value) {
			addCriterion("SERIAL <>", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialGreaterThan(Integer value) {
			addCriterion("SERIAL >", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialGreaterThanOrEqualTo(Integer value) {
			addCriterion("SERIAL >=", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialLessThan(Integer value) {
			addCriterion("SERIAL <", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialLessThanOrEqualTo(Integer value) {
			addCriterion("SERIAL <=", value, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialIn(List<Integer> values) {
			addCriterion("SERIAL in", values, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialNotIn(List<Integer> values) {
			addCriterion("SERIAL not in", values, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialBetween(Integer value1, Integer value2) {
			addCriterion("SERIAL between", value1, value2, "serial");
			return (Criteria) this;
		}

		public Criteria andSerialNotBetween(Integer value1, Integer value2) {
			addCriterion("SERIAL not between", value1, value2, "serial");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table DICTIONARY_
	 * @mbggenerated  Thu Jul 07 15:48:12 CST 2011
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KSOURCE.DICTIONARY
     *
     * @mbggenerated do_not_delete_during_merge Wed May 11 21:56:58 CST 2011
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}