package com.ksource.liangfa.domain;

public class DiscretionStandard {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private Integer standardId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.BASIS_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private Integer basisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.TERM_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private Integer termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.DISCRETION_LEVEL
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private Integer discretionLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.ILLEGAL_SITUATION
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private String illegalSituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private String standard;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD_ID
     *
     * @return the value of LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public Integer getStandardId() {
        return standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD_ID
     *
     * @param standardId the value for LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.BASIS_ID
     *
     * @return the value of LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.BASIS_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public Integer getBasisId() {
        return basisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.BASIS_ID
     *
     * @param basisId the value for LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.BASIS_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setBasisId(Integer basisId) {
        this.basisId = basisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.TERM_ID
     *
     * @return the value of LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.TERM_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public Integer getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.TERM_ID
     *
     * @param termId the value for LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.TERM_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setTermId(Integer termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.DISCRETION_LEVEL
     *
     * @return the value of LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.DISCRETION_LEVEL
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public Integer getDiscretionLevel() {
        return discretionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.DISCRETION_LEVEL
     *
     * @param discretionLevel the value for LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.DISCRETION_LEVEL
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setDiscretionLevel(Integer discretionLevel) {
        this.discretionLevel = discretionLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.ILLEGAL_SITUATION
     *
     * @return the value of LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.ILLEGAL_SITUATION
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public String getIllegalSituation() {
        return illegalSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.ILLEGAL_SITUATION
     *
     * @param illegalSituation the value for LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.ILLEGAL_SITUATION
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setIllegalSituation(String illegalSituation) {
        this.illegalSituation = illegalSituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD
     *
     * @return the value of LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public String getStandard() {
        return standard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD
     *
     * @param standard the value for LIANGFA_XINXIANG20170222.DISCRETION_STANDARD.STANDARD
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setStandard(String standard) {
        this.standard = standard;
    }
    
    //行业类型
    private String industryType;
    //处罚依据项内容
    private String termInfo;

	public String getIndustryType() {
		return industryType;
	}

	public void setIndustryType(String industryType) {
		this.industryType = industryType;
	}

	public String getTermInfo() {
		return termInfo;
	}

	public void setTermInfo(String termInfo) {
		this.termInfo = termInfo;
	}
    
}