package com.ksource.liangfa.domain;

import java.util.List;

public class DistrictExternal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_CODE
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    private String districtCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_NAME
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    private String districtName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.UP_DISTRICT_CODE
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    private String upDistrictCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.JB
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    private Integer jb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.SERIAL
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    private Integer serial;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_CODE
     *
     * @return the value of LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_CODE
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public String getDistrictCode() {
        return districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_CODE
     *
     * @param districtCode the value for LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_CODE
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public void setDistrictCode(String districtCode) {
        this.districtCode = districtCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_NAME
     *
     * @return the value of LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_NAME
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public String getDistrictName() {
        return districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_NAME
     *
     * @param districtName the value for LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.DISTRICT_NAME
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public void setDistrictName(String districtName) {
        this.districtName = districtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.UP_DISTRICT_CODE
     *
     * @return the value of LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.UP_DISTRICT_CODE
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public String getUpDistrictCode() {
        return upDistrictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.UP_DISTRICT_CODE
     *
     * @param upDistrictCode the value for LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.UP_DISTRICT_CODE
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public void setUpDistrictCode(String upDistrictCode) {
        this.upDistrictCode = upDistrictCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.JB
     *
     * @return the value of LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.JB
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public Integer getJb() {
        return jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.JB
     *
     * @param jb the value for LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.JB
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public void setJb(Integer jb) {
        this.jb = jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.SERIAL
     *
     * @return the value of LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.SERIAL
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public Integer getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.SERIAL
     *
     * @param serial the value for LIANGFA_HUBEI20160322.DISTRICT_EXTERNAL.SERIAL
     *
     * @mbggenerated Fri Mar 25 09:51:43 CST 2016
     */
    public void setSerial(Integer serial) {
        this.serial = serial;
    }

    public Integer chirdNum;
    public Integer orgNum;

    public List<Organise> orgs;
    
   	public Integer getChirdNum() {
   		return chirdNum;
   	}

   	public void setChirdNum(Integer chirdNum) {
   		this.chirdNum = chirdNum;
   	}

	public Integer getOrgNum() {
		return orgNum;
	}

	public void setOrgNum(Integer orgNum) {
		this.orgNum = orgNum;
	}

	public List<Organise> getOrgs() {
		return orgs;
	}

	public void setOrgs(List<Organise> orgs) {
		this.orgs = orgs;
	}
   	
}