package com.ksource.liangfa.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ForumCommunityExample {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public ForumCommunityExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("ID is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("ID is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("ID =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("ID <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("ID >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("ID >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("ID <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("ID <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("ID in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("ID not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("ID between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("ID not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("NAME is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("NAME is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("NAME =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("NAME <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("NAME >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("NAME >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("NAME <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("NAME <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("NAME like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("NAME not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("NAME in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("NAME not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("NAME between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("NAME not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNoteIsNull() {
			addCriterion("NOTE is null");
			return (Criteria) this;
		}

		public Criteria andNoteIsNotNull() {
			addCriterion("NOTE is not null");
			return (Criteria) this;
		}

		public Criteria andNoteEqualTo(String value) {
			addCriterion("NOTE =", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotEqualTo(String value) {
			addCriterion("NOTE <>", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThan(String value) {
			addCriterion("NOTE >", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteGreaterThanOrEqualTo(String value) {
			addCriterion("NOTE >=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThan(String value) {
			addCriterion("NOTE <", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLessThanOrEqualTo(String value) {
			addCriterion("NOTE <=", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteLike(String value) {
			addCriterion("NOTE like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotLike(String value) {
			addCriterion("NOTE not like", value, "note");
			return (Criteria) this;
		}

		public Criteria andNoteIn(List<String> values) {
			addCriterion("NOTE in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotIn(List<String> values) {
			addCriterion("NOTE not in", values, "note");
			return (Criteria) this;
		}

		public Criteria andNoteBetween(String value1, String value2) {
			addCriterion("NOTE between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andNoteNotBetween(String value1, String value2) {
			addCriterion("NOTE not between", value1, value2, "note");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("CREATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("CREATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("CREATE_TIME =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("CREATE_TIME <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("CREATE_TIME >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("CREATE_TIME <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("CREATE_TIME <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("CREATE_TIME in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("CREATE_TIME not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("CREATE_TIME not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("UPDATE_TIME is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("UPDATE_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("UPDATE_TIME =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("UPDATE_TIME <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("UPDATE_TIME >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("UPDATE_TIME <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("UPDATE_TIME <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("UPDATE_TIME in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("UPDATE_TIME not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("UPDATE_TIME not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeIsNull() {
			addCriterion("LATEST_THEME is null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeIsNotNull() {
			addCriterion("LATEST_THEME is not null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeEqualTo(Integer value) {
			addCriterion("LATEST_THEME =", value, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNotEqualTo(Integer value) {
			addCriterion("LATEST_THEME <>", value, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeGreaterThan(Integer value) {
			addCriterion("LATEST_THEME >", value, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeGreaterThanOrEqualTo(Integer value) {
			addCriterion("LATEST_THEME >=", value, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeLessThan(Integer value) {
			addCriterion("LATEST_THEME <", value, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeLessThanOrEqualTo(Integer value) {
			addCriterion("LATEST_THEME <=", value, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeIn(List<Integer> values) {
			addCriterion("LATEST_THEME in", values, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNotIn(List<Integer> values) {
			addCriterion("LATEST_THEME not in", values, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeBetween(Integer value1, Integer value2) {
			addCriterion("LATEST_THEME between", value1, value2, "latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNotBetween(Integer value1, Integer value2) {
			addCriterion("LATEST_THEME not between", value1, value2,
					"latestTheme");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameIsNull() {
			addCriterion("LATEST_THEME_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameIsNotNull() {
			addCriterion("LATEST_THEME_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameEqualTo(String value) {
			addCriterion("LATEST_THEME_NAME =", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameNotEqualTo(String value) {
			addCriterion("LATEST_THEME_NAME <>", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameGreaterThan(String value) {
			addCriterion("LATEST_THEME_NAME >", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameGreaterThanOrEqualTo(String value) {
			addCriterion("LATEST_THEME_NAME >=", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameLessThan(String value) {
			addCriterion("LATEST_THEME_NAME <", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameLessThanOrEqualTo(String value) {
			addCriterion("LATEST_THEME_NAME <=", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameLike(String value) {
			addCriterion("LATEST_THEME_NAME like", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameNotLike(String value) {
			addCriterion("LATEST_THEME_NAME not like", value, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameIn(List<String> values) {
			addCriterion("LATEST_THEME_NAME in", values, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameNotIn(List<String> values) {
			addCriterion("LATEST_THEME_NAME not in", values, "latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameBetween(String value1, String value2) {
			addCriterion("LATEST_THEME_NAME between", value1, value2,
					"latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeNameNotBetween(String value1,
				String value2) {
			addCriterion("LATEST_THEME_NAME not between", value1, value2,
					"latestThemeName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeIsNull() {
			addCriterion("LATEST_THEME_TIME is null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeIsNotNull() {
			addCriterion("LATEST_THEME_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeEqualTo(Date value) {
			addCriterion("LATEST_THEME_TIME =", value, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeNotEqualTo(Date value) {
			addCriterion("LATEST_THEME_TIME <>", value, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeGreaterThan(Date value) {
			addCriterion("LATEST_THEME_TIME >", value, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("LATEST_THEME_TIME >=", value, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeLessThan(Date value) {
			addCriterion("LATEST_THEME_TIME <", value, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeLessThanOrEqualTo(Date value) {
			addCriterion("LATEST_THEME_TIME <=", value, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeIn(List<Date> values) {
			addCriterion("LATEST_THEME_TIME in", values, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeNotIn(List<Date> values) {
			addCriterion("LATEST_THEME_TIME not in", values, "latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeBetween(Date value1, Date value2) {
			addCriterion("LATEST_THEME_TIME between", value1, value2,
					"latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeTimeNotBetween(Date value1, Date value2) {
			addCriterion("LATEST_THEME_TIME not between", value1, value2,
					"latestThemeTime");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerIsNull() {
			addCriterion("LATEST_THEME_INPUTER is null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerIsNotNull() {
			addCriterion("LATEST_THEME_INPUTER is not null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerEqualTo(String value) {
			addCriterion("LATEST_THEME_INPUTER =", value, "latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNotEqualTo(String value) {
			addCriterion("LATEST_THEME_INPUTER <>", value, "latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerGreaterThan(String value) {
			addCriterion("LATEST_THEME_INPUTER >", value, "latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerGreaterThanOrEqualTo(String value) {
			addCriterion("LATEST_THEME_INPUTER >=", value, "latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerLessThan(String value) {
			addCriterion("LATEST_THEME_INPUTER <", value, "latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerLessThanOrEqualTo(String value) {
			addCriterion("LATEST_THEME_INPUTER <=", value, "latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerLike(String value) {
			addCriterion("LATEST_THEME_INPUTER like", value,
					"latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNotLike(String value) {
			addCriterion("LATEST_THEME_INPUTER not like", value,
					"latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerIn(List<String> values) {
			addCriterion("LATEST_THEME_INPUTER in", values,
					"latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNotIn(List<String> values) {
			addCriterion("LATEST_THEME_INPUTER not in", values,
					"latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerBetween(String value1,
				String value2) {
			addCriterion("LATEST_THEME_INPUTER between", value1, value2,
					"latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNotBetween(String value1,
				String value2) {
			addCriterion("LATEST_THEME_INPUTER not between", value1, value2,
					"latestThemeInputer");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameIsNull() {
			addCriterion("LATEST_THEME_INPUTER_NAME is null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameIsNotNull() {
			addCriterion("LATEST_THEME_INPUTER_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameEqualTo(String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME =", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameNotEqualTo(String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME <>", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameGreaterThan(String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME >", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameGreaterThanOrEqualTo(
				String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME >=", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameLessThan(String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME <", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameLessThanOrEqualTo(String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME <=", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameLike(String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME like", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameNotLike(String value) {
			addCriterion("LATEST_THEME_INPUTER_NAME not like", value,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameIn(List<String> values) {
			addCriterion("LATEST_THEME_INPUTER_NAME in", values,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameNotIn(List<String> values) {
			addCriterion("LATEST_THEME_INPUTER_NAME not in", values,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameBetween(String value1,
				String value2) {
			addCriterion("LATEST_THEME_INPUTER_NAME between", value1, value2,
					"latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andLatestThemeInputerNameNotBetween(String value1,
				String value2) {
			addCriterion("LATEST_THEME_INPUTER_NAME not between", value1,
					value2, "latestThemeInputerName");
			return (Criteria) this;
		}

		public Criteria andIconPathIsNull() {
			addCriterion("ICON_PATH is null");
			return (Criteria) this;
		}

		public Criteria andIconPathIsNotNull() {
			addCriterion("ICON_PATH is not null");
			return (Criteria) this;
		}

		public Criteria andIconPathEqualTo(String value) {
			addCriterion("ICON_PATH =", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathNotEqualTo(String value) {
			addCriterion("ICON_PATH <>", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathGreaterThan(String value) {
			addCriterion("ICON_PATH >", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathGreaterThanOrEqualTo(String value) {
			addCriterion("ICON_PATH >=", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathLessThan(String value) {
			addCriterion("ICON_PATH <", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathLessThanOrEqualTo(String value) {
			addCriterion("ICON_PATH <=", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathLike(String value) {
			addCriterion("ICON_PATH like", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathNotLike(String value) {
			addCriterion("ICON_PATH not like", value, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathIn(List<String> values) {
			addCriterion("ICON_PATH in", values, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathNotIn(List<String> values) {
			addCriterion("ICON_PATH not in", values, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathBetween(String value1, String value2) {
			addCriterion("ICON_PATH between", value1, value2, "iconPath");
			return (Criteria) this;
		}

		public Criteria andIconPathNotBetween(String value1, String value2) {
			addCriterion("ICON_PATH not between", value1, value2, "iconPath");
			return (Criteria) this;
		}

		public Criteria andThemeCountIsNull() {
			addCriterion("THEME_COUNT is null");
			return (Criteria) this;
		}

		public Criteria andThemeCountIsNotNull() {
			addCriterion("THEME_COUNT is not null");
			return (Criteria) this;
		}

		public Criteria andThemeCountEqualTo(Integer value) {
			addCriterion("THEME_COUNT =", value, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountNotEqualTo(Integer value) {
			addCriterion("THEME_COUNT <>", value, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountGreaterThan(Integer value) {
			addCriterion("THEME_COUNT >", value, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("THEME_COUNT >=", value, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountLessThan(Integer value) {
			addCriterion("THEME_COUNT <", value, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountLessThanOrEqualTo(Integer value) {
			addCriterion("THEME_COUNT <=", value, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountIn(List<Integer> values) {
			addCriterion("THEME_COUNT in", values, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountNotIn(List<Integer> values) {
			addCriterion("THEME_COUNT not in", values, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountBetween(Integer value1, Integer value2) {
			addCriterion("THEME_COUNT between", value1, value2, "themeCount");
			return (Criteria) this;
		}

		public Criteria andThemeCountNotBetween(Integer value1, Integer value2) {
			addCriterion("THEME_COUNT not between", value1, value2,
					"themeCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountIsNull() {
			addCriterion("REPLY_COUNT is null");
			return (Criteria) this;
		}

		public Criteria andReplyCountIsNotNull() {
			addCriterion("REPLY_COUNT is not null");
			return (Criteria) this;
		}

		public Criteria andReplyCountEqualTo(Integer value) {
			addCriterion("REPLY_COUNT =", value, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountNotEqualTo(Integer value) {
			addCriterion("REPLY_COUNT <>", value, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountGreaterThan(Integer value) {
			addCriterion("REPLY_COUNT >", value, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("REPLY_COUNT >=", value, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountLessThan(Integer value) {
			addCriterion("REPLY_COUNT <", value, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountLessThanOrEqualTo(Integer value) {
			addCriterion("REPLY_COUNT <=", value, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountIn(List<Integer> values) {
			addCriterion("REPLY_COUNT in", values, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountNotIn(List<Integer> values) {
			addCriterion("REPLY_COUNT not in", values, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountBetween(Integer value1, Integer value2) {
			addCriterion("REPLY_COUNT between", value1, value2, "replyCount");
			return (Criteria) this;
		}

		public Criteria andReplyCountNotBetween(Integer value1, Integer value2) {
			addCriterion("REPLY_COUNT not between", value1, value2,
					"replyCount");
			return (Criteria) this;
		}

		public Criteria andStateIsNull() {
			addCriterion("STATE is null");
			return (Criteria) this;
		}

		public Criteria andStateIsNotNull() {
			addCriterion("STATE is not null");
			return (Criteria) this;
		}

		public Criteria andStateEqualTo(Integer value) {
			addCriterion("STATE =", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotEqualTo(Integer value) {
			addCriterion("STATE <>", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThan(Integer value) {
			addCriterion("STATE >", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("STATE >=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThan(Integer value) {
			addCriterion("STATE <", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateLessThanOrEqualTo(Integer value) {
			addCriterion("STATE <=", value, "state");
			return (Criteria) this;
		}

		public Criteria andStateIn(List<Integer> values) {
			addCriterion("STATE in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotIn(List<Integer> values) {
			addCriterion("STATE not in", values, "state");
			return (Criteria) this;
		}

		public Criteria andStateBetween(Integer value1, Integer value2) {
			addCriterion("STATE between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andStateNotBetween(Integer value1, Integer value2) {
			addCriterion("STATE not between", value1, value2, "state");
			return (Criteria) this;
		}

		public Criteria andSortIsNull() {
			addCriterion("SORT is null");
			return (Criteria) this;
		}

		public Criteria andSortIsNotNull() {
			addCriterion("SORT is not null");
			return (Criteria) this;
		}

		public Criteria andSortEqualTo(Integer value) {
			addCriterion("SORT =", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotEqualTo(Integer value) {
			addCriterion("SORT <>", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThan(Integer value) {
			addCriterion("SORT >", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortGreaterThanOrEqualTo(Integer value) {
			addCriterion("SORT >=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThan(Integer value) {
			addCriterion("SORT <", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortLessThanOrEqualTo(Integer value) {
			addCriterion("SORT <=", value, "sort");
			return (Criteria) this;
		}

		public Criteria andSortIn(List<Integer> values) {
			addCriterion("SORT in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotIn(List<Integer> values) {
			addCriterion("SORT not in", values, "sort");
			return (Criteria) this;
		}

		public Criteria andSortBetween(Integer value1, Integer value2) {
			addCriterion("SORT between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andSortNotBetween(Integer value1, Integer value2) {
			addCriterion("SORT not between", value1, value2, "sort");
			return (Criteria) this;
		}

		public Criteria andIconStyleIsNull() {
			addCriterion("ICON_STYLE is null");
			return (Criteria) this;
		}

		public Criteria andIconStyleIsNotNull() {
			addCriterion("ICON_STYLE is not null");
			return (Criteria) this;
		}

		public Criteria andIconStyleEqualTo(String value) {
			addCriterion("ICON_STYLE =", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotEqualTo(String value) {
			addCriterion("ICON_STYLE <>", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleGreaterThan(String value) {
			addCriterion("ICON_STYLE >", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleGreaterThanOrEqualTo(String value) {
			addCriterion("ICON_STYLE >=", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleLessThan(String value) {
			addCriterion("ICON_STYLE <", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleLessThanOrEqualTo(String value) {
			addCriterion("ICON_STYLE <=", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleLike(String value) {
			addCriterion("ICON_STYLE like", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotLike(String value) {
			addCriterion("ICON_STYLE not like", value, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleIn(List<String> values) {
			addCriterion("ICON_STYLE in", values, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotIn(List<String> values) {
			addCriterion("ICON_STYLE not in", values, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleBetween(String value1, String value2) {
			addCriterion("ICON_STYLE between", value1, value2, "iconStyle");
			return (Criteria) this;
		}

		public Criteria andIconStyleNotBetween(String value1, String value2) {
			addCriterion("ICON_STYLE not between", value1, value2, "iconStyle");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table FORUM_SECTION
	 * @mbggenerated  Wed Feb 08 10:40:27 CST 2012
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	protected String desc;
	
	public String getDesc() {
		return desc;
	}

	public void setDesc(String desc) {
		this.desc = desc;
	}

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table FORUM_SECTION
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 07 14:51:05 CST 2012
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}