package com.ksource.liangfa.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PenaltyCaseFormExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public PenaltyCaseFormExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andCaseIdIsNull() {
			addCriterion("CASE_ID is null");
			return (Criteria) this;
		}

		public Criteria andCaseIdIsNotNull() {
			addCriterion("CASE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andCaseIdEqualTo(String value) {
			addCriterion("CASE_ID =", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotEqualTo(String value) {
			addCriterion("CASE_ID <>", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThan(String value) {
			addCriterion("CASE_ID >", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdGreaterThanOrEqualTo(String value) {
			addCriterion("CASE_ID >=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThan(String value) {
			addCriterion("CASE_ID <", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLessThanOrEqualTo(String value) {
			addCriterion("CASE_ID <=", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdLike(String value) {
			addCriterion("CASE_ID like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotLike(String value) {
			addCriterion("CASE_ID not like", value, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdIn(List<String> values) {
			addCriterion("CASE_ID in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotIn(List<String> values) {
			addCriterion("CASE_ID not in", values, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdBetween(String value1, String value2) {
			addCriterion("CASE_ID between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andCaseIdNotBetween(String value1, String value2) {
			addCriterion("CASE_ID not between", value1, value2, "caseId");
			return (Criteria) this;
		}

		public Criteria andUndertakerIsNull() {
			addCriterion("UNDERTAKER is null");
			return (Criteria) this;
		}

		public Criteria andUndertakerIsNotNull() {
			addCriterion("UNDERTAKER is not null");
			return (Criteria) this;
		}

		public Criteria andUndertakerEqualTo(String value) {
			addCriterion("UNDERTAKER =", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerNotEqualTo(String value) {
			addCriterion("UNDERTAKER <>", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerGreaterThan(String value) {
			addCriterion("UNDERTAKER >", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerGreaterThanOrEqualTo(String value) {
			addCriterion("UNDERTAKER >=", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerLessThan(String value) {
			addCriterion("UNDERTAKER <", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerLessThanOrEqualTo(String value) {
			addCriterion("UNDERTAKER <=", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerLike(String value) {
			addCriterion("UNDERTAKER like", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerNotLike(String value) {
			addCriterion("UNDERTAKER not like", value, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerIn(List<String> values) {
			addCriterion("UNDERTAKER in", values, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerNotIn(List<String> values) {
			addCriterion("UNDERTAKER not in", values, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerBetween(String value1, String value2) {
			addCriterion("UNDERTAKER between", value1, value2, "undertaker");
			return (Criteria) this;
		}

		public Criteria andUndertakerNotBetween(String value1, String value2) {
			addCriterion("UNDERTAKER not between", value1, value2, "undertaker");
			return (Criteria) this;
		}

		public Criteria andChufaTimeIsNull() {
			addCriterion("CHUFA_TIME is null");
			return (Criteria) this;
		}

		public Criteria andChufaTimeIsNotNull() {
			addCriterion("CHUFA_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andChufaTimeEqualTo(Date value) {
			addCriterion("CHUFA_TIME =", value, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeNotEqualTo(Date value) {
			addCriterion("CHUFA_TIME <>", value, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeGreaterThan(Date value) {
			addCriterion("CHUFA_TIME >", value, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("CHUFA_TIME >=", value, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeLessThan(Date value) {
			addCriterion("CHUFA_TIME <", value, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeLessThanOrEqualTo(Date value) {
			addCriterion("CHUFA_TIME <=", value, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeIn(List<Date> values) {
			addCriterion("CHUFA_TIME in", values, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeNotIn(List<Date> values) {
			addCriterion("CHUFA_TIME not in", values, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeBetween(Date value1, Date value2) {
			addCriterion("CHUFA_TIME between", value1, value2, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimeNotBetween(Date value1, Date value2) {
			addCriterion("CHUFA_TIME not between", value1, value2, "chufaTime");
			return (Criteria) this;
		}

		public Criteria andChufaTimesIsNull() {
			addCriterion("CHUFA_TIMES is null");
			return (Criteria) this;
		}

		public Criteria andChufaTimesIsNotNull() {
			addCriterion("CHUFA_TIMES is not null");
			return (Criteria) this;
		}

		public Criteria andChufaTimesEqualTo(Integer value) {
			addCriterion("CHUFA_TIMES =", value, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesNotEqualTo(Integer value) {
			addCriterion("CHUFA_TIMES <>", value, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesGreaterThan(Integer value) {
			addCriterion("CHUFA_TIMES >", value, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesGreaterThanOrEqualTo(Integer value) {
			addCriterion("CHUFA_TIMES >=", value, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesLessThan(Integer value) {
			addCriterion("CHUFA_TIMES <", value, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesLessThanOrEqualTo(Integer value) {
			addCriterion("CHUFA_TIMES <=", value, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesIn(List<Integer> values) {
			addCriterion("CHUFA_TIMES in", values, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesNotIn(List<Integer> values) {
			addCriterion("CHUFA_TIMES not in", values, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesBetween(Integer value1, Integer value2) {
			addCriterion("CHUFA_TIMES between", value1, value2, "chufaTimes");
			return (Criteria) this;
		}

		public Criteria andChufaTimesNotBetween(Integer value1, Integer value2) {
			addCriterion("CHUFA_TIMES not between", value1, value2,
					"chufaTimes");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoIsNull() {
			addCriterion("PENALTY_FILE_NO is null");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoIsNotNull() {
			addCriterion("PENALTY_FILE_NO is not null");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoEqualTo(String value) {
			addCriterion("PENALTY_FILE_NO =", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoNotEqualTo(String value) {
			addCriterion("PENALTY_FILE_NO <>", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoGreaterThan(String value) {
			addCriterion("PENALTY_FILE_NO >", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoGreaterThanOrEqualTo(String value) {
			addCriterion("PENALTY_FILE_NO >=", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoLessThan(String value) {
			addCriterion("PENALTY_FILE_NO <", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoLessThanOrEqualTo(String value) {
			addCriterion("PENALTY_FILE_NO <=", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoLike(String value) {
			addCriterion("PENALTY_FILE_NO like", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoNotLike(String value) {
			addCriterion("PENALTY_FILE_NO not like", value, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoIn(List<String> values) {
			addCriterion("PENALTY_FILE_NO in", values, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoNotIn(List<String> values) {
			addCriterion("PENALTY_FILE_NO not in", values, "penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoBetween(String value1, String value2) {
			addCriterion("PENALTY_FILE_NO between", value1, value2,
					"penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileNoNotBetween(String value1, String value2) {
			addCriterion("PENALTY_FILE_NO not between", value1, value2,
					"penaltyFileNo");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdIsNull() {
			addCriterion("PENALTY_FILE_ID is null");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdIsNotNull() {
			addCriterion("PENALTY_FILE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdEqualTo(Integer value) {
			addCriterion("PENALTY_FILE_ID =", value, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdNotEqualTo(Integer value) {
			addCriterion("PENALTY_FILE_ID <>", value, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdGreaterThan(Integer value) {
			addCriterion("PENALTY_FILE_ID >", value, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("PENALTY_FILE_ID >=", value, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdLessThan(Integer value) {
			addCriterion("PENALTY_FILE_ID <", value, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdLessThanOrEqualTo(Integer value) {
			addCriterion("PENALTY_FILE_ID <=", value, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdIn(List<Integer> values) {
			addCriterion("PENALTY_FILE_ID in", values, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdNotIn(List<Integer> values) {
			addCriterion("PENALTY_FILE_ID not in", values, "penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdBetween(Integer value1, Integer value2) {
			addCriterion("PENALTY_FILE_ID between", value1, value2,
					"penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andPenaltyFileIdNotBetween(Integer value1,
				Integer value2) {
			addCriterion("PENALTY_FILE_ID not between", value1, value2,
					"penaltyFileId");
			return (Criteria) this;
		}

		public Criteria andIsDescussIsNull() {
			addCriterion("IS_DESCUSS is null");
			return (Criteria) this;
		}

		public Criteria andIsDescussIsNotNull() {
			addCriterion("IS_DESCUSS is not null");
			return (Criteria) this;
		}

		public Criteria andIsDescussEqualTo(Integer value) {
			addCriterion("IS_DESCUSS =", value, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussNotEqualTo(Integer value) {
			addCriterion("IS_DESCUSS <>", value, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussGreaterThan(Integer value) {
			addCriterion("IS_DESCUSS >", value, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussGreaterThanOrEqualTo(Integer value) {
			addCriterion("IS_DESCUSS >=", value, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussLessThan(Integer value) {
			addCriterion("IS_DESCUSS <", value, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussLessThanOrEqualTo(Integer value) {
			addCriterion("IS_DESCUSS <=", value, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussIn(List<Integer> values) {
			addCriterion("IS_DESCUSS in", values, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussNotIn(List<Integer> values) {
			addCriterion("IS_DESCUSS not in", values, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussBetween(Integer value1, Integer value2) {
			addCriterion("IS_DESCUSS between", value1, value2, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsDescussNotBetween(Integer value1, Integer value2) {
			addCriterion("IS_DESCUSS not between", value1, value2, "isDescuss");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseIsNull() {
			addCriterion("IS_SERIOUS_CASE is null");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseIsNotNull() {
			addCriterion("IS_SERIOUS_CASE is not null");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseEqualTo(Integer value) {
			addCriterion("IS_SERIOUS_CASE =", value, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseNotEqualTo(Integer value) {
			addCriterion("IS_SERIOUS_CASE <>", value, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseGreaterThan(Integer value) {
			addCriterion("IS_SERIOUS_CASE >", value, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseGreaterThanOrEqualTo(Integer value) {
			addCriterion("IS_SERIOUS_CASE >=", value, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseLessThan(Integer value) {
			addCriterion("IS_SERIOUS_CASE <", value, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseLessThanOrEqualTo(Integer value) {
			addCriterion("IS_SERIOUS_CASE <=", value, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseIn(List<Integer> values) {
			addCriterion("IS_SERIOUS_CASE in", values, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseNotIn(List<Integer> values) {
			addCriterion("IS_SERIOUS_CASE not in", values, "isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseBetween(Integer value1, Integer value2) {
			addCriterion("IS_SERIOUS_CASE between", value1, value2,
					"isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsSeriousCaseNotBetween(Integer value1,
				Integer value2) {
			addCriterion("IS_SERIOUS_CASE not between", value1, value2,
					"isSeriousCase");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyIsNull() {
			addCriterion("IS_BEYOND_EIGHTY is null");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyIsNotNull() {
			addCriterion("IS_BEYOND_EIGHTY is not null");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyEqualTo(Integer value) {
			addCriterion("IS_BEYOND_EIGHTY =", value, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyNotEqualTo(Integer value) {
			addCriterion("IS_BEYOND_EIGHTY <>", value, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyGreaterThan(Integer value) {
			addCriterion("IS_BEYOND_EIGHTY >", value, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyGreaterThanOrEqualTo(Integer value) {
			addCriterion("IS_BEYOND_EIGHTY >=", value, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyLessThan(Integer value) {
			addCriterion("IS_BEYOND_EIGHTY <", value, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyLessThanOrEqualTo(Integer value) {
			addCriterion("IS_BEYOND_EIGHTY <=", value, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyIn(List<Integer> values) {
			addCriterion("IS_BEYOND_EIGHTY in", values, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyNotIn(List<Integer> values) {
			addCriterion("IS_BEYOND_EIGHTY not in", values, "isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyBetween(Integer value1, Integer value2) {
			addCriterion("IS_BEYOND_EIGHTY between", value1, value2,
					"isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andIsBeyondEightyNotBetween(Integer value1,
				Integer value2) {
			addCriterion("IS_BEYOND_EIGHTY not between", value1, value2,
					"isBeyondEighty");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdIsNull() {
			addCriterion("CHUFA_TYPE_ID is null");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdIsNotNull() {
			addCriterion("CHUFA_TYPE_ID is not null");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdEqualTo(String value) {
			addCriterion("CHUFA_TYPE_ID =", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdNotEqualTo(String value) {
			addCriterion("CHUFA_TYPE_ID <>", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdGreaterThan(String value) {
			addCriterion("CHUFA_TYPE_ID >", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdGreaterThanOrEqualTo(String value) {
			addCriterion("CHUFA_TYPE_ID >=", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdLessThan(String value) {
			addCriterion("CHUFA_TYPE_ID <", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdLessThanOrEqualTo(String value) {
			addCriterion("CHUFA_TYPE_ID <=", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdLike(String value) {
			addCriterion("CHUFA_TYPE_ID like", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdNotLike(String value) {
			addCriterion("CHUFA_TYPE_ID not like", value, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdIn(List<String> values) {
			addCriterion("CHUFA_TYPE_ID in", values, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdNotIn(List<String> values) {
			addCriterion("CHUFA_TYPE_ID not in", values, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdBetween(String value1, String value2) {
			addCriterion("CHUFA_TYPE_ID between", value1, value2, "chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeIdNotBetween(String value1, String value2) {
			addCriterion("CHUFA_TYPE_ID not between", value1, value2,
					"chufaTypeId");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameIsNull() {
			addCriterion("CHUFA_TYPE_NAME is null");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameIsNotNull() {
			addCriterion("CHUFA_TYPE_NAME is not null");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameEqualTo(String value) {
			addCriterion("CHUFA_TYPE_NAME =", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameNotEqualTo(String value) {
			addCriterion("CHUFA_TYPE_NAME <>", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameGreaterThan(String value) {
			addCriterion("CHUFA_TYPE_NAME >", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameGreaterThanOrEqualTo(String value) {
			addCriterion("CHUFA_TYPE_NAME >=", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameLessThan(String value) {
			addCriterion("CHUFA_TYPE_NAME <", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameLessThanOrEqualTo(String value) {
			addCriterion("CHUFA_TYPE_NAME <=", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameLike(String value) {
			addCriterion("CHUFA_TYPE_NAME like", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameNotLike(String value) {
			addCriterion("CHUFA_TYPE_NAME not like", value, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameIn(List<String> values) {
			addCriterion("CHUFA_TYPE_NAME in", values, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameNotIn(List<String> values) {
			addCriterion("CHUFA_TYPE_NAME not in", values, "chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameBetween(String value1, String value2) {
			addCriterion("CHUFA_TYPE_NAME between", value1, value2,
					"chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaTypeNameNotBetween(String value1, String value2) {
			addCriterion("CHUFA_TYPE_NAME not between", value1, value2,
					"chufaTypeName");
			return (Criteria) this;
		}

		public Criteria andChufaBasisIsNull() {
			addCriterion("CHUFA_BASIS is null");
			return (Criteria) this;
		}

		public Criteria andChufaBasisIsNotNull() {
			addCriterion("CHUFA_BASIS is not null");
			return (Criteria) this;
		}

		public Criteria andChufaBasisEqualTo(String value) {
			addCriterion("CHUFA_BASIS =", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisNotEqualTo(String value) {
			addCriterion("CHUFA_BASIS <>", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisGreaterThan(String value) {
			addCriterion("CHUFA_BASIS >", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisGreaterThanOrEqualTo(String value) {
			addCriterion("CHUFA_BASIS >=", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisLessThan(String value) {
			addCriterion("CHUFA_BASIS <", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisLessThanOrEqualTo(String value) {
			addCriterion("CHUFA_BASIS <=", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisLike(String value) {
			addCriterion("CHUFA_BASIS like", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisNotLike(String value) {
			addCriterion("CHUFA_BASIS not like", value, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisIn(List<String> values) {
			addCriterion("CHUFA_BASIS in", values, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisNotIn(List<String> values) {
			addCriterion("CHUFA_BASIS not in", values, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisBetween(String value1, String value2) {
			addCriterion("CHUFA_BASIS between", value1, value2, "chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaBasisNotBetween(String value1, String value2) {
			addCriterion("CHUFA_BASIS not between", value1, value2,
					"chufaBasis");
			return (Criteria) this;
		}

		public Criteria andChufaResultIsNull() {
			addCriterion("CHUFA_RESULT is null");
			return (Criteria) this;
		}

		public Criteria andChufaResultIsNotNull() {
			addCriterion("CHUFA_RESULT is not null");
			return (Criteria) this;
		}

		public Criteria andChufaResultEqualTo(String value) {
			addCriterion("CHUFA_RESULT =", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultNotEqualTo(String value) {
			addCriterion("CHUFA_RESULT <>", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultGreaterThan(String value) {
			addCriterion("CHUFA_RESULT >", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultGreaterThanOrEqualTo(String value) {
			addCriterion("CHUFA_RESULT >=", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultLessThan(String value) {
			addCriterion("CHUFA_RESULT <", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultLessThanOrEqualTo(String value) {
			addCriterion("CHUFA_RESULT <=", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultLike(String value) {
			addCriterion("CHUFA_RESULT like", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultNotLike(String value) {
			addCriterion("CHUFA_RESULT not like", value, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultIn(List<String> values) {
			addCriterion("CHUFA_RESULT in", values, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultNotIn(List<String> values) {
			addCriterion("CHUFA_RESULT not in", values, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultBetween(String value1, String value2) {
			addCriterion("CHUFA_RESULT between", value1, value2, "chufaResult");
			return (Criteria) this;
		}

		public Criteria andChufaResultNotBetween(String value1, String value2) {
			addCriterion("CHUFA_RESULT not between", value1, value2,
					"chufaResult");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyIsNull() {
			addCriterion("IS_LOWER_LIMIT_MONEY is null");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyIsNotNull() {
			addCriterion("IS_LOWER_LIMIT_MONEY is not null");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyEqualTo(Integer value) {
			addCriterion("IS_LOWER_LIMIT_MONEY =", value, "isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyNotEqualTo(Integer value) {
			addCriterion("IS_LOWER_LIMIT_MONEY <>", value, "isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyGreaterThan(Integer value) {
			addCriterion("IS_LOWER_LIMIT_MONEY >", value, "isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyGreaterThanOrEqualTo(Integer value) {
			addCriterion("IS_LOWER_LIMIT_MONEY >=", value, "isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyLessThan(Integer value) {
			addCriterion("IS_LOWER_LIMIT_MONEY <", value, "isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyLessThanOrEqualTo(Integer value) {
			addCriterion("IS_LOWER_LIMIT_MONEY <=", value, "isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyIn(List<Integer> values) {
			addCriterion("IS_LOWER_LIMIT_MONEY in", values, "isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyNotIn(List<Integer> values) {
			addCriterion("IS_LOWER_LIMIT_MONEY not in", values,
					"isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyBetween(Integer value1,
				Integer value2) {
			addCriterion("IS_LOWER_LIMIT_MONEY between", value1, value2,
					"isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsLowerLimitMoneyNotBetween(Integer value1,
				Integer value2) {
			addCriterion("IS_LOWER_LIMIT_MONEY not between", value1, value2,
					"isLowerLimitMoney");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyIsNull() {
			addCriterion("IS_IDENTIFY is null");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyIsNotNull() {
			addCriterion("IS_IDENTIFY is not null");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyEqualTo(Integer value) {
			addCriterion("IS_IDENTIFY =", value, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyNotEqualTo(Integer value) {
			addCriterion("IS_IDENTIFY <>", value, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyGreaterThan(Integer value) {
			addCriterion("IS_IDENTIFY >", value, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyGreaterThanOrEqualTo(Integer value) {
			addCriterion("IS_IDENTIFY >=", value, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyLessThan(Integer value) {
			addCriterion("IS_IDENTIFY <", value, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyLessThanOrEqualTo(Integer value) {
			addCriterion("IS_IDENTIFY <=", value, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyIn(List<Integer> values) {
			addCriterion("IS_IDENTIFY in", values, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyNotIn(List<Integer> values) {
			addCriterion("IS_IDENTIFY not in", values, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyBetween(Integer value1, Integer value2) {
			addCriterion("IS_IDENTIFY between", value1, value2, "isIdentify");
			return (Criteria) this;
		}

		public Criteria andIsIdentifyNotBetween(Integer value1, Integer value2) {
			addCriterion("IS_IDENTIFY not between", value1, value2,
					"isIdentify");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeIsNull() {
			addCriterion("IDENTIFY_TYPE is null");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeIsNotNull() {
			addCriterion("IDENTIFY_TYPE is not null");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeEqualTo(Integer value) {
			addCriterion("IDENTIFY_TYPE =", value, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeNotEqualTo(Integer value) {
			addCriterion("IDENTIFY_TYPE <>", value, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeGreaterThan(Integer value) {
			addCriterion("IDENTIFY_TYPE >", value, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("IDENTIFY_TYPE >=", value, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeLessThan(Integer value) {
			addCriterion("IDENTIFY_TYPE <", value, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeLessThanOrEqualTo(Integer value) {
			addCriterion("IDENTIFY_TYPE <=", value, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeIn(List<Integer> values) {
			addCriterion("IDENTIFY_TYPE in", values, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeNotIn(List<Integer> values) {
			addCriterion("IDENTIFY_TYPE not in", values, "identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeBetween(Integer value1, Integer value2) {
			addCriterion("IDENTIFY_TYPE between", value1, value2,
					"identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("IDENTIFY_TYPE not between", value1, value2,
					"identifyType");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgIsNull() {
			addCriterion("IDENTIFY_ORG is null");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgIsNotNull() {
			addCriterion("IDENTIFY_ORG is not null");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgEqualTo(String value) {
			addCriterion("IDENTIFY_ORG =", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgNotEqualTo(String value) {
			addCriterion("IDENTIFY_ORG <>", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgGreaterThan(String value) {
			addCriterion("IDENTIFY_ORG >", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgGreaterThanOrEqualTo(String value) {
			addCriterion("IDENTIFY_ORG >=", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgLessThan(String value) {
			addCriterion("IDENTIFY_ORG <", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgLessThanOrEqualTo(String value) {
			addCriterion("IDENTIFY_ORG <=", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgLike(String value) {
			addCriterion("IDENTIFY_ORG like", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgNotLike(String value) {
			addCriterion("IDENTIFY_ORG not like", value, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgIn(List<String> values) {
			addCriterion("IDENTIFY_ORG in", values, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgNotIn(List<String> values) {
			addCriterion("IDENTIFY_ORG not in", values, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgBetween(String value1, String value2) {
			addCriterion("IDENTIFY_ORG between", value1, value2, "identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyOrgNotBetween(String value1, String value2) {
			addCriterion("IDENTIFY_ORG not between", value1, value2,
					"identifyOrg");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonIsNull() {
			addCriterion("IDENTIFY_PERSON is null");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonIsNotNull() {
			addCriterion("IDENTIFY_PERSON is not null");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonEqualTo(String value) {
			addCriterion("IDENTIFY_PERSON =", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonNotEqualTo(String value) {
			addCriterion("IDENTIFY_PERSON <>", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonGreaterThan(String value) {
			addCriterion("IDENTIFY_PERSON >", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonGreaterThanOrEqualTo(String value) {
			addCriterion("IDENTIFY_PERSON >=", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonLessThan(String value) {
			addCriterion("IDENTIFY_PERSON <", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonLessThanOrEqualTo(String value) {
			addCriterion("IDENTIFY_PERSON <=", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonLike(String value) {
			addCriterion("IDENTIFY_PERSON like", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonNotLike(String value) {
			addCriterion("IDENTIFY_PERSON not like", value, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonIn(List<String> values) {
			addCriterion("IDENTIFY_PERSON in", values, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonNotIn(List<String> values) {
			addCriterion("IDENTIFY_PERSON not in", values, "identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonBetween(String value1, String value2) {
			addCriterion("IDENTIFY_PERSON between", value1, value2,
					"identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyPersonNotBetween(String value1, String value2) {
			addCriterion("IDENTIFY_PERSON not between", value1, value2,
					"identifyPerson");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeIsNull() {
			addCriterion("IDENTIFY_TIME is null");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeIsNotNull() {
			addCriterion("IDENTIFY_TIME is not null");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeEqualTo(Date value) {
			addCriterion("IDENTIFY_TIME =", value, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeNotEqualTo(Date value) {
			addCriterion("IDENTIFY_TIME <>", value, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeGreaterThan(Date value) {
			addCriterion("IDENTIFY_TIME >", value, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("IDENTIFY_TIME >=", value, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeLessThan(Date value) {
			addCriterion("IDENTIFY_TIME <", value, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("IDENTIFY_TIME <=", value, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeIn(List<Date> values) {
			addCriterion("IDENTIFY_TIME in", values, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeNotIn(List<Date> values) {
			addCriterion("IDENTIFY_TIME not in", values, "identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeBetween(Date value1, Date value2) {
			addCriterion("IDENTIFY_TIME between", value1, value2,
					"identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("IDENTIFY_TIME not between", value1, value2,
					"identifyTime");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultIsNull() {
			addCriterion("IDENTIFY_RESULT is null");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultIsNotNull() {
			addCriterion("IDENTIFY_RESULT is not null");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultEqualTo(String value) {
			addCriterion("IDENTIFY_RESULT =", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultNotEqualTo(String value) {
			addCriterion("IDENTIFY_RESULT <>", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultGreaterThan(String value) {
			addCriterion("IDENTIFY_RESULT >", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultGreaterThanOrEqualTo(String value) {
			addCriterion("IDENTIFY_RESULT >=", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultLessThan(String value) {
			addCriterion("IDENTIFY_RESULT <", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultLessThanOrEqualTo(String value) {
			addCriterion("IDENTIFY_RESULT <=", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultLike(String value) {
			addCriterion("IDENTIFY_RESULT like", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultNotLike(String value) {
			addCriterion("IDENTIFY_RESULT not like", value, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultIn(List<String> values) {
			addCriterion("IDENTIFY_RESULT in", values, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultNotIn(List<String> values) {
			addCriterion("IDENTIFY_RESULT not in", values, "identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultBetween(String value1, String value2) {
			addCriterion("IDENTIFY_RESULT between", value1, value2,
					"identifyResult");
			return (Criteria) this;
		}

		public Criteria andIdentifyResultNotBetween(String value1, String value2) {
			addCriterion("IDENTIFY_RESULT not between", value1, value2,
					"identifyResult");
			return (Criteria) this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("MEMO is null");
			return (Criteria) this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("MEMO is not null");
			return (Criteria) this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("MEMO =", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("MEMO <>", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("MEMO >", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("MEMO >=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("MEMO <", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("MEMO <=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("MEMO like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("MEMO not like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoIn(List<String> values) {
			addCriterion("MEMO in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotIn(List<String> values) {
			addCriterion("MEMO not in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("MEMO between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("MEMO not between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedIsNull() {
			addCriterion("GOODS_INVOLVED is null");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedIsNotNull() {
			addCriterion("GOODS_INVOLVED is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedEqualTo(String value) {
			addCriterion("GOODS_INVOLVED =", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedNotEqualTo(String value) {
			addCriterion("GOODS_INVOLVED <>", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedGreaterThan(String value) {
			addCriterion("GOODS_INVOLVED >", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedGreaterThanOrEqualTo(String value) {
			addCriterion("GOODS_INVOLVED >=", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedLessThan(String value) {
			addCriterion("GOODS_INVOLVED <", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedLessThanOrEqualTo(String value) {
			addCriterion("GOODS_INVOLVED <=", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedLike(String value) {
			addCriterion("GOODS_INVOLVED like", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedNotLike(String value) {
			addCriterion("GOODS_INVOLVED not like", value, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedIn(List<String> values) {
			addCriterion("GOODS_INVOLVED in", values, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedNotIn(List<String> values) {
			addCriterion("GOODS_INVOLVED not in", values, "goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedBetween(String value1, String value2) {
			addCriterion("GOODS_INVOLVED between", value1, value2,
					"goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsInvolvedNotBetween(String value1, String value2) {
			addCriterion("GOODS_INVOLVED not between", value1, value2,
					"goodsInvolved");
			return (Criteria) this;
		}

		public Criteria andGoodsCountIsNull() {
			addCriterion("GOODS_COUNT is null");
			return (Criteria) this;
		}

		public Criteria andGoodsCountIsNotNull() {
			addCriterion("GOODS_COUNT is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsCountEqualTo(String value) {
			addCriterion("GOODS_COUNT =", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountNotEqualTo(String value) {
			addCriterion("GOODS_COUNT <>", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountGreaterThan(String value) {
			addCriterion("GOODS_COUNT >", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountGreaterThanOrEqualTo(String value) {
			addCriterion("GOODS_COUNT >=", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountLessThan(String value) {
			addCriterion("GOODS_COUNT <", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountLessThanOrEqualTo(String value) {
			addCriterion("GOODS_COUNT <=", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountLike(String value) {
			addCriterion("GOODS_COUNT like", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountNotLike(String value) {
			addCriterion("GOODS_COUNT not like", value, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountIn(List<String> values) {
			addCriterion("GOODS_COUNT in", values, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountNotIn(List<String> values) {
			addCriterion("GOODS_COUNT not in", values, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountBetween(String value1, String value2) {
			addCriterion("GOODS_COUNT between", value1, value2, "goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsCountNotBetween(String value1, String value2) {
			addCriterion("GOODS_COUNT not between", value1, value2,
					"goodsCount");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultIsNull() {
			addCriterion("GOODS_DISPOSE_RESULT is null");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultIsNotNull() {
			addCriterion("GOODS_DISPOSE_RESULT is not null");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultEqualTo(String value) {
			addCriterion("GOODS_DISPOSE_RESULT =", value, "goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultNotEqualTo(String value) {
			addCriterion("GOODS_DISPOSE_RESULT <>", value, "goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultGreaterThan(String value) {
			addCriterion("GOODS_DISPOSE_RESULT >", value, "goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultGreaterThanOrEqualTo(String value) {
			addCriterion("GOODS_DISPOSE_RESULT >=", value, "goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultLessThan(String value) {
			addCriterion("GOODS_DISPOSE_RESULT <", value, "goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultLessThanOrEqualTo(String value) {
			addCriterion("GOODS_DISPOSE_RESULT <=", value, "goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultLike(String value) {
			addCriterion("GOODS_DISPOSE_RESULT like", value,
					"goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultNotLike(String value) {
			addCriterion("GOODS_DISPOSE_RESULT not like", value,
					"goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultIn(List<String> values) {
			addCriterion("GOODS_DISPOSE_RESULT in", values,
					"goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultNotIn(List<String> values) {
			addCriterion("GOODS_DISPOSE_RESULT not in", values,
					"goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultBetween(String value1,
				String value2) {
			addCriterion("GOODS_DISPOSE_RESULT between", value1, value2,
					"goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andGoodsDisposeResultNotBetween(String value1,
				String value2) {
			addCriterion("GOODS_DISPOSE_RESULT not between", value1, value2,
					"goodsDisposeResult");
			return (Criteria) this;
		}

		public Criteria andIsDqdjIsNull() {
			addCriterion("IS_DQDJ is null");
			return (Criteria) this;
		}

		public Criteria andIsDqdjIsNotNull() {
			addCriterion("IS_DQDJ is not null");
			return (Criteria) this;
		}

		public Criteria andIsDqdjEqualTo(Integer value) {
			addCriterion("IS_DQDJ =", value, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjNotEqualTo(Integer value) {
			addCriterion("IS_DQDJ <>", value, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjGreaterThan(Integer value) {
			addCriterion("IS_DQDJ >", value, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjGreaterThanOrEqualTo(Integer value) {
			addCriterion("IS_DQDJ >=", value, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjLessThan(Integer value) {
			addCriterion("IS_DQDJ <", value, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjLessThanOrEqualTo(Integer value) {
			addCriterion("IS_DQDJ <=", value, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjIn(List<Integer> values) {
			addCriterion("IS_DQDJ in", values, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjNotIn(List<Integer> values) {
			addCriterion("IS_DQDJ not in", values, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjBetween(Integer value1, Integer value2) {
			addCriterion("IS_DQDJ between", value1, value2, "isDqdj");
			return (Criteria) this;
		}

		public Criteria andIsDqdjNotBetween(Integer value1, Integer value2) {
			addCriterion("IS_DQDJ not between", value1, value2, "isDqdj");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
	 * @mbggenerated  Thu Mar 23 17:31:38 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table LIANGFA_XINXIANG20170222.PENALTY_CASE_FORM
     *
     * @mbggenerated do_not_delete_during_merge Mon Mar 20 19:10:49 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}