package com.ksource.liangfa.domain;

public class PunishBasisTerm {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private Integer termId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.BASIS_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private Integer basisId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_INFO
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    private String termInfo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_ID
     *
     * @return the value of LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public Integer getTermId() {
        return termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_ID
     *
     * @param termId the value for LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setTermId(Integer termId) {
        this.termId = termId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.BASIS_ID
     *
     * @return the value of LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.BASIS_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public Integer getBasisId() {
        return basisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.BASIS_ID
     *
     * @param basisId the value for LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.BASIS_ID
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setBasisId(Integer basisId) {
        this.basisId = basisId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_INFO
     *
     * @return the value of LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_INFO
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public String getTermInfo() {
        return termInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_INFO
     *
     * @param termInfo the value for LIANGFA_XINXIANG20170222.PUNISH_BASIS_TERM.TERM_INFO
     *
     * @mbggenerated Mon Mar 27 13:54:08 CST 2017
     */
    public void setTermInfo(String termInfo) {
        this.termInfo = termInfo;
    }
    
}