package com.ksource.liangfa.domain;

import java.util.Date;
import java.util.List;

public class SpecialActivity {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ID
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUTER
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private String inputer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.LIANGFA_LEADER_CODE
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private Integer liangfaLeaderCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.START_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private Date startTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.END_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private Date endTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUT_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private Date inputTime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private String attachmentName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_PATH
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private String attachmentPath;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.DETAIL_NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	private String detailName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ID
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ID
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ID
	 * @param id  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ID
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.NAME
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.NAME
	 * @param name  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUTER
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUTER
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public String getInputer() {
		return inputer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUTER
	 * @param inputer  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUTER
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setInputer(String inputer) {
		this.inputer = inputer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.LIANGFA_LEADER_CODE
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.LIANGFA_LEADER_CODE
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public Integer getLiangfaLeaderCode() {
		return liangfaLeaderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.LIANGFA_LEADER_CODE
	 * @param liangfaLeaderCode  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.LIANGFA_LEADER_CODE
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setLiangfaLeaderCode(Integer liangfaLeaderCode) {
		this.liangfaLeaderCode = liangfaLeaderCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.START_TIME
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.START_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public Date getStartTime() {
		return startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.START_TIME
	 * @param startTime  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.START_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.END_TIME
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.END_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public Date getEndTime() {
		return endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.END_TIME
	 * @param endTime  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.END_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUT_TIME
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUT_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public Date getInputTime() {
		return inputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUT_TIME
	 * @param inputTime  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.INPUT_TIME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setInputTime(Date inputTime) {
		this.inputTime = inputTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_NAME
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public String getAttachmentName() {
		return attachmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_NAME
	 * @param attachmentName  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setAttachmentName(String attachmentName) {
		this.attachmentName = attachmentName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_PATH
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_PATH
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public String getAttachmentPath() {
		return attachmentPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_PATH
	 * @param attachmentPath  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.ATTACHMENT_PATH
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setAttachmentPath(String attachmentPath) {
		this.attachmentPath = attachmentPath;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.DETAIL_NAME
	 * @return  the value of LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.DETAIL_NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public String getDetailName() {
		return detailName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.DETAIL_NAME
	 * @param detailName  the value for LIANGFA_HUBEI_TEST.SPECIAL_ACTIVITY.DETAIL_NAME
	 * @mbggenerated  Mon Dec 09 17:29:10 CST 2013
	 */
	public void setDetailName(String detailName) {
		this.detailName = detailName;
	}

	public String getLiangfaLeaderName() {
		return liangfaLeaderName;
	}

	public void setLiangfaLeaderName(String liangfaLeaderName) {
		this.liangfaLeaderName = liangfaLeaderName;
	}

	public List<ActivityMember> getMemberList() {
		return memberList;
	}

	public void setMemberList(List<ActivityMember> memberList) {
		this.memberList = memberList;
	}

	private String liangfaLeaderName;
	
	private List<ActivityMember> memberList;
	
}