package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.CaseIllegalSituation;
import com.ksource.liangfa.domain.CaseIllegalSituationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseIllegalSituationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ILLEGAL_SITUATION
     *
     * @mbggenerated Wed Mar 02 15:53:04 CST 2016
     */
    int countByExample(CaseIllegalSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ILLEGAL_SITUATION
     *
     * @mbggenerated Wed Mar 02 15:53:04 CST 2016
     */
    int deleteByExample(CaseIllegalSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ILLEGAL_SITUATION
     *
     * @mbggenerated Wed Mar 02 15:53:04 CST 2016
     */
    int insert(CaseIllegalSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ILLEGAL_SITUATION
     *
     * @mbggenerated Wed Mar 02 15:53:04 CST 2016
     */
    int insertSelective(CaseIllegalSituation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ILLEGAL_SITUATION
     *
     * @mbggenerated Wed Mar 02 15:53:04 CST 2016
     */
    List<CaseIllegalSituation> selectByExample(CaseIllegalSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ILLEGAL_SITUATION
     *
     * @mbggenerated Wed Mar 02 15:53:04 CST 2016
     */
    int updateByExampleSelective(@Param("record") CaseIllegalSituation record, @Param("example") CaseIllegalSituationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ILLEGAL_SITUATION
     *
     * @mbggenerated Wed Mar 02 15:53:04 CST 2016
     */
    int updateByExample(@Param("record") CaseIllegalSituation record, @Param("example") CaseIllegalSituationExample example);
}