package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.CaseModifiedImpLog;
import com.ksource.liangfa.domain.CaseModifiedImpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.ksource.liangfa.domain.CaseModifiedImpLogWithBLOBs;

public interface CaseModifiedImpLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	int countByExample(CaseModifiedImpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	int deleteByExample(CaseModifiedImpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	int insert(CaseModifiedImpLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	int insertSelective(CaseModifiedImpLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	List<CaseModifiedImpLogWithBLOBs> selectByExampleWithBLOBs(
			CaseModifiedImpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	List<CaseModifiedImpLog> selectByExample(CaseModifiedImpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	int updateByExampleSelective(
			@Param("record") CaseModifiedImpLogWithBLOBs record,
			@Param("example") CaseModifiedImpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	int updateByExampleWithBLOBs(
			@Param("record") CaseModifiedImpLogWithBLOBs record,
			@Param("example") CaseModifiedImpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_MODIFIED_IMP_LOG
	 * @mbggenerated  Fri Sep 26 09:10:19 CST 2014
	 */
	int updateByExample(@Param("record") CaseModifiedImpLog record,
			@Param("example") CaseModifiedImpLogExample example);

	List<CaseModifiedImpLogWithBLOBs> getById(Integer id);
}