package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.CaseConsultation;
import com.ksource.liangfa.domain.CaseConsultationExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CaseConsultationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int countByExample(CaseConsultationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int deleteByExample(CaseConsultationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int insert(CaseConsultation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int insertSelective(CaseConsultation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	List<CaseConsultation> selectByExampleWithBLOBs(
			CaseConsultationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	List<CaseConsultation> selectByExample(CaseConsultationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	CaseConsultation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int updateByExampleSelective(@Param("record") CaseConsultation record,
			@Param("example") CaseConsultationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int updateByExampleWithBLOBs(@Param("record") CaseConsultation record,
			@Param("example") CaseConsultationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int updateByExample(@Param("record") CaseConsultation record,
			@Param("example") CaseConsultationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int updateByPrimaryKeySelective(CaseConsultation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int updateByPrimaryKeyWithBLOBs(CaseConsultation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_CONSULTATION
	 * @mbggenerated  Tue Dec 27 11:46:25 CST 2011
	 */
	int updateByPrimaryKey(CaseConsultation record);

	List<CaseConsultation> getToDoList(Map<String, Object> map);

	CaseConsultation selectByPK(Integer caseConsultationId);
}