package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.CaseTodo;
import com.ksource.liangfa.domain.CaseYisongJiwei;
import com.ksource.liangfa.domain.CaseYisongJiweiExample;
import com.ksource.liangfa.domain.Organise;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface CaseYisongJiweiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int countByExample(CaseYisongJiweiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int deleteByExample(CaseYisongJiweiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int deleteByPrimaryKey(String yisongId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int insert(CaseYisongJiwei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int insertSelective(CaseYisongJiwei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    List<CaseYisongJiwei> selectByExample(CaseYisongJiweiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    CaseYisongJiwei selectByPrimaryKey(String yisongId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int updateByExampleSelective(@Param("record") CaseYisongJiwei record, @Param("example") CaseYisongJiweiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int updateByExample(@Param("record") CaseYisongJiwei record, @Param("example") CaseYisongJiweiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int updateByPrimaryKeySelective(CaseYisongJiwei record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LIANGFA_XINXIANG20170222.CASE_YISONG_JIWEI
     *
     * @mbggenerated Thu Mar 30 11:45:27 CST 2017
     */
    int updateByPrimaryKey(CaseYisongJiwei record);

	void addYisongjieweiCase(CaseYisongJiwei caseYisongJiwei);

	int getCaseYisongNum(Integer orgId);
	
	/**
	 * 移送纪委案件
	 * @param paramMap
	 * @return
	 */
    List<CaseYisongJiwei> getCaseYisongList(Map<String,Object> paramMap);
    
    int getCaseYisongCount(Map<String,Object> paramMap);

	int getExistCase(String caseId);

}