package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.CaseSupervision;
import com.ksource.liangfa.domain.CaseSupervisionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CaseSupervisionMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_SUPERVISION
	 * @mbggenerated  Fri Nov 30 10:19:24 CST 2012
	 */
	int countByExample(CaseSupervisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_SUPERVISION
	 * @mbggenerated  Fri Nov 30 10:19:24 CST 2012
	 */
	int deleteByExample(CaseSupervisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_SUPERVISION
	 * @mbggenerated  Fri Nov 30 10:19:24 CST 2012
	 */
	int insert(CaseSupervision record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_SUPERVISION
	 * @mbggenerated  Fri Nov 30 10:19:24 CST 2012
	 */
	int insertSelective(CaseSupervision record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_SUPERVISION
	 * @mbggenerated  Fri Nov 30 10:19:24 CST 2012
	 */
	List<CaseSupervision> selectByExample(CaseSupervisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_SUPERVISION
	 * @mbggenerated  Fri Nov 30 10:19:24 CST 2012
	 */
	int updateByExampleSelective(@Param("record") CaseSupervision record,
			@Param("example") CaseSupervisionExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table CASE_SUPERVISION
	 * @mbggenerated  Fri Nov 30 10:19:24 CST 2012
	 */
	int updateByExample(@Param("record") CaseSupervision record,
			@Param("example") CaseSupervisionExample example);

	public List<CaseSupervision> caseSupervisionNotice(String userId);
}