package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.CaseModifiedExpLog;
import com.ksource.liangfa.domain.CaseModifiedExpLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.ksource.liangfa.domain.CaseModifiedExpLogWithBLOBs;

public interface CaseModifiedExpLogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int countByExample(CaseModifiedExpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int deleteByExample(CaseModifiedExpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int deleteByPrimaryKey(Long logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int insert(CaseModifiedExpLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int insertSelective(CaseModifiedExpLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	List<CaseModifiedExpLogWithBLOBs> selectByExampleWithBLOBs(
			CaseModifiedExpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	List<CaseModifiedExpLog> selectByExample(CaseModifiedExpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	CaseModifiedExpLogWithBLOBs selectByPrimaryKey(Long logId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int updateByExampleSelective(
			@Param("record") CaseModifiedExpLogWithBLOBs record,
			@Param("example") CaseModifiedExpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int updateByExampleWithBLOBs(
			@Param("record") CaseModifiedExpLogWithBLOBs record,
			@Param("example") CaseModifiedExpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int updateByExample(@Param("record") CaseModifiedExpLog record,
			@Param("example") CaseModifiedExpLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int updateByPrimaryKeySelective(CaseModifiedExpLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int updateByPrimaryKeyWithBLOBs(CaseModifiedExpLogWithBLOBs record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_MODIFIED_EXP_LOG
	 * @mbggenerated  Fri Sep 26 11:21:14 CST 2014
	 */
	int updateByPrimaryKey(CaseModifiedExpLog record);

	CaseModifiedExpLogWithBLOBs selectByLogId(Long logId);

	CaseModifiedExpLogWithBLOBs selectLastExportLog(String userId);
}