package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.CaseAttachment;
import com.ksource.liangfa.domain.CaseAttachmentExample;
import com.ksource.liangfa.domain.CaseAttachmentKey;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;
import java.math.BigDecimal;

public interface CaseAttachmentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int countByExample(CaseAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int deleteByExample(CaseAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int insert(CaseAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int insertSelective(CaseAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	List<CaseAttachment> selectByExample(CaseAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	CaseAttachment selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int updateByExampleSelective(@Param("record") CaseAttachment record,
			@Param("example") CaseAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int updateByExample(@Param("record") CaseAttachment record,
			@Param("example") CaseAttachmentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int updateByPrimaryKeySelective(CaseAttachment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI_V2_XIAN.CASE_ATTACHMENT
	 * @mbggenerated  Thu Sep 25 11:42:46 CST 2014
	 */
	int updateByPrimaryKey(CaseAttachment record);

	List<CaseAttachment> queryNoExportDataList(Map<String, Object> paramMap);
}