package com.ksource.liangfa.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.ksource.liangfa.domain.cms.CmsFriendlyLink;
import com.ksource.liangfa.domain.cms.CmsFriendlyLinkExample;

public interface CmsFriendlyLinkMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int countByExample(CmsFriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int deleteByExample(CmsFriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int deleteByPrimaryKey(Integer linkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int insert(CmsFriendlyLink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int insertSelective(CmsFriendlyLink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	List<CmsFriendlyLink> selectByExample(CmsFriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	CmsFriendlyLink selectByPrimaryKey(Integer linkId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int updateByExampleSelective(@Param("record") CmsFriendlyLink record,
			@Param("example") CmsFriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int updateByExample(@Param("record") CmsFriendlyLink record,
			@Param("example") CmsFriendlyLinkExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int updateByPrimaryKeySelective(CmsFriendlyLink record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FRIENDLY_LINK
	 * @mbggenerated  Mon May 13 11:00:20 CST 2013
	 */
	int updateByPrimaryKey(CmsFriendlyLink record);

	List<CmsFriendlyLink> queryCmsFriendlyLink();
}