package com.ksource.liangfa.mapper;

import com.ksource.common.bean.PaginationHelper;
import com.ksource.liangfa.domain.CommunionReceive;
import com.ksource.liangfa.domain.CommunionReceiveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CommunionReceiveMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int countByExample(CommunionReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int deleteByExample(CommunionReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int deleteByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int insert(CommunionReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int insertSelective(CommunionReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    List<CommunionReceive> selectByExampleWithBLOBs(
            CommunionReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    List<CommunionReceive> selectByExample(CommunionReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    CommunionReceive selectByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int updateByExampleSelective(@Param("record") CommunionReceive record,
            @Param("example") CommunionReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") CommunionReceive record,
            @Param("example") CommunionReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int updateByExample(@Param("record") CommunionReceive record,
            @Param("example") CommunionReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int updateByPrimaryKeySelective(CommunionReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(CommunionReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.COMMUNION_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:49 CST 2017
     */
    int updateByPrimaryKey(CommunionReceive record);

    List<CommunionReceive> getCommunionReceiveList(CommunionReceive communionReceive);
}