package com.ksource.liangfa.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.ksource.liangfa.domain.FieldInstance;
import com.ksource.liangfa.domain.FieldInstanceExample;
import com.ksource.liangfa.domain.FieldInstanceKey;

public interface FieldInstanceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int countByExample(FieldInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int deleteByExample(FieldInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int deleteByPrimaryKey(FieldInstanceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int insert(FieldInstance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int insertSelective(FieldInstance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	List<FieldInstance> selectByExample(FieldInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	FieldInstance selectByPrimaryKey(FieldInstanceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int updateByExampleSelective(@Param("record") FieldInstance record,
			@Param("example") FieldInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int updateByExample(@Param("record") FieldInstance record,
			@Param("example") FieldInstanceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int updateByPrimaryKeySelective(FieldInstance record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table FIELD_INSTANCE
	 * @mbggenerated  Tue Jul 17 14:35:02 CST 2012
	 */
	int updateByPrimaryKey(FieldInstance record);

	List<FieldInstance> queryNoExportDataList(Map<String, Object> paramMap);

    List<FieldInstance> selectByTaskInstId(@Param("taskInstId") String taskInstId);
}