package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.InstructionReceive;
import com.ksource.liangfa.domain.InstructionReceiveExample;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface InstructionReceiveMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int countByExample(InstructionReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int deleteByExample(InstructionReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int deleteByPrimaryKey(Integer receiveId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int insert(InstructionReceive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int insertSelective(InstructionReceive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	List<InstructionReceive> selectByExampleWithBLOBs(
			InstructionReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	List<InstructionReceive> selectByExample(InstructionReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	InstructionReceive selectByPrimaryKey(Integer receiveId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int updateByExampleSelective(@Param("record") InstructionReceive record,
			@Param("example") InstructionReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int updateByExampleWithBLOBs(@Param("record") InstructionReceive record,
			@Param("example") InstructionReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int updateByExample(@Param("record") InstructionReceive record,
			@Param("example") InstructionReceiveExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int updateByPrimaryKeySelective(InstructionReceive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int updateByPrimaryKeyWithBLOBs(InstructionReceive record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160322.INSTRUCTION_RECEIVE
	 * @mbggenerated  Sat Mar 26 11:05:06 CST 2016
	 */
	int updateByPrimaryKey(InstructionReceive record);

	List<InstructionReceive> queryReceiveInstruction(InstructionReceive record);

	List<InstructionReceive> queryAll(InstructionReceive instructionReceive);


	/**
	 * 下发指令统计
	 * author XT
	 * @param paramMap
	 * @return
	 */
	Map<String, Object> queryInstructionStatis(Map<String, Object> paramMap);

	/**
	 * 各院下发指令及办理情况统计
	 * author XT
	 * @param paramMap
	 * @return
	 */
	List<Map<String, Object>> queryInstructionStatisByOrg(
			Map<String, Object> paramMap);
	
}