package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.MailFile;
import com.ksource.liangfa.domain.MailFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.ksource.liangfa.domain.MailFile;
import com.ksource.liangfa.domain.MailFileExample;

public interface MailFileMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int countByExample(MailFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int deleteByExample(MailFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int deleteByPrimaryKey(Integer fileId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int insert(MailFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int insertSelective(MailFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	List<MailFile> selectByExample(MailFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	MailFile selectByPrimaryKey(Integer fileId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByExampleSelective(@Param("record") MailFile record,
                                 @Param("example") MailFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByExample(@Param("record") MailFile record,
                        @Param("example") MailFileExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByPrimaryKeySelective(MailFile record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_FILE
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByPrimaryKey(MailFile record);
}