package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.MailReceivedInfo;
import com.ksource.liangfa.domain.MailReceivedInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import com.ksource.liangfa.domain.MailReceivedInfo;
import com.ksource.liangfa.domain.MailReceivedInfoExample;

public interface MailReceivedInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int countByExample(MailReceivedInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int deleteByExample(MailReceivedInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int deleteByPrimaryKey(Integer receivedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int insert(MailReceivedInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int insertSelective(MailReceivedInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	List<MailReceivedInfo> selectByExampleWithBLOBs(
            MailReceivedInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	List<MailReceivedInfo> selectByExample(MailReceivedInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	MailReceivedInfo selectByPrimaryKey(Integer receivedId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByExampleSelective(@Param("record") MailReceivedInfo record,
                                 @Param("example") MailReceivedInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByExampleWithBLOBs(@Param("record") MailReceivedInfo record,
                                 @Param("example") MailReceivedInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByExample(@Param("record") MailReceivedInfo record,
                        @Param("example") MailReceivedInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByPrimaryKeySelective(MailReceivedInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByPrimaryKeyWithBLOBs(MailReceivedInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LF_MAIL_RECEIVED_INFO
	 * @mbggenerated  Tue Jan 29 10:43:17 CST 2013
	 */
	int updateByPrimaryKey(MailReceivedInfo record);

	List<MailReceivedInfo> findByReciveder(String userId);

    MailReceivedInfo findById(Integer id);
}