package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.OfficeTemplate;
import com.ksource.liangfa.domain.OfficeTemplateExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface OfficeTemplateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int countByExample(OfficeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int deleteByExample(OfficeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int insert(OfficeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int insertSelective(OfficeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	List<OfficeTemplate> selectByExample(OfficeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	OfficeTemplate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int updateByExampleSelective(@Param("record") OfficeTemplate record,
			@Param("example") OfficeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int updateByExample(@Param("record") OfficeTemplate record,
			@Param("example") OfficeTemplateExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int updateByPrimaryKeySelective(OfficeTemplate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_HUBEI20160811.OFFICE_TEMPLATE
	 * @mbggenerated  Fri Sep 02 10:38:31 CST 2016
	 */
	int updateByPrimaryKey(OfficeTemplate record);
	
	OfficeTemplate checkDocType(Map<String,Object> param);
}