package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.ProcDiagram;
import com.ksource.liangfa.domain.ProcDiagramExample;
import com.ksource.liangfa.domain.ProcDiagramKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcDiagramMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int countByExample(ProcDiagramExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int deleteByExample(ProcDiagramExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int deleteByPrimaryKey(ProcDiagramKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int insert(ProcDiagram record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int insertSelective(ProcDiagram record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	List<ProcDiagram> selectByExample(ProcDiagramExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	ProcDiagram selectByPrimaryKey(ProcDiagramKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int updateByExampleSelective(@Param("record") ProcDiagram record,
			@Param("example") ProcDiagramExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int updateByExample(@Param("record") ProcDiagram record,
			@Param("example") ProcDiagramExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int updateByPrimaryKeySelective(ProcDiagram record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table PROC_DIAGRAM
	 * @mbggenerated  Thu May 12 14:25:05 CST 2011
	 */
	int updateByPrimaryKey(ProcDiagram record);
	
	List<ProcDiagram> selectProcDiagramAndTaskBindByProcDefId(String procDefId);
}