package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.ProcSequence;
import com.ksource.liangfa.domain.ProcSequenceExample;
import com.ksource.liangfa.domain.ProcSequenceKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProcSequenceMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int countByExample(ProcSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int deleteByExample(ProcSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int deleteByPrimaryKey(ProcSequenceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int insert(ProcSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int insertSelective(ProcSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	List<ProcSequence> selectByExample(ProcSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	ProcSequence selectByPrimaryKey(ProcSequenceKey key);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int updateByExampleSelective(@Param("record") ProcSequence record,
			@Param("example") ProcSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int updateByExample(@Param("record") ProcSequence record,
			@Param("example") ProcSequenceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int updateByPrimaryKeySelective(ProcSequence record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170421.PROC_SEQUENCE
	 * @mbggenerated  Sat Apr 22 16:00:37 CST 2017
	 */
	int updateByPrimaryKey(ProcSequence record);
}