package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.PunishBasis;
import com.ksource.liangfa.domain.PunishBasisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PunishBasisMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int countByExample(PunishBasisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int deleteByExample(PunishBasisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int deleteByPrimaryKey(Integer basisId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int insert(PunishBasis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int insertSelective(PunishBasis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	List<PunishBasis> selectByExampleWithBLOBs(PunishBasisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	List<PunishBasis> selectByExample(PunishBasisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	PunishBasis selectByPrimaryKey(Integer basisId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int updateByExampleSelective(@Param("record") PunishBasis record,
			@Param("example") PunishBasisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") PunishBasis record,
			@Param("example") PunishBasisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int updateByExample(@Param("record") PunishBasis record,
			@Param("example") PunishBasisExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int updateByPrimaryKeySelective(PunishBasis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(PunishBasis record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170222.PUNISH_BASIS
	 * @mbggenerated  Mon Mar 27 14:31:27 CST 2017
	 */
	int updateByPrimaryKey(PunishBasis record);
}