package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.WebForum;
import com.ksource.liangfa.domain.WebForumExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WebForumMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int countByExample(WebForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int deleteByExample(WebForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int deleteByPrimaryKey(Integer forumId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int insert(WebForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int insertSelective(WebForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	List<WebForum> selectByExample(WebForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	WebForum selectByPrimaryKey(Integer forumId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int updateByExampleSelective(@Param("record") WebForum record,
			@Param("example") WebForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int updateByExample(@Param("record") WebForum record,
			@Param("example") WebForumExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int updateByPrimaryKeySelective(WebForum record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table WEB_FORUM
	 * @mbggenerated  Fri Nov 02 09:21:40 CST 2012
	 */
	int updateByPrimaryKey(WebForum record);

	List<WebForum> list();
}