package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.WorkReportReceive;
import com.ksource.liangfa.domain.WorkReportReceiveExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface WorkReportReceiveMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int countByExample(WorkReportReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int deleteByExample(WorkReportReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int deleteByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int insert(WorkReportReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int insertSelective(WorkReportReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    List<WorkReportReceive> selectByExampleWithBLOBs(
            WorkReportReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    List<WorkReportReceive> selectByExample(WorkReportReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    WorkReportReceive selectByPrimaryKey(Integer receiveId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int updateByExampleSelective(@Param("record") WorkReportReceive record,
            @Param("example") WorkReportReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int updateByExampleWithBLOBs(@Param("record") WorkReportReceive record,
            @Param("example") WorkReportReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int updateByExample(@Param("record") WorkReportReceive record,
            @Param("example") WorkReportReceiveExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int updateByPrimaryKeySelective(WorkReportReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int updateByPrimaryKeyWithBLOBs(WorkReportReceive record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table LIANGFA_XINXIANG20170424.WORK_REPORT_RECEIVE
     * @mbggenerated  Thu Jul 27 15:56:08 CST 2017
     */
    int updateByPrimaryKey(WorkReportReceive record);

    List<WorkReportReceive> getWorkReportReceiveList(WorkReportReceive workReportReceive);
    
    /**
     * 根据reportId查询WorkReportReceive信息
     * @param map
     * @return
     */
    List<WorkReportReceive> getListByReportId(Map<String,Object> map);
}