package com.ksource.liangfa.mapper;

import com.ksource.liangfa.domain.ZhifaInfo;
import com.ksource.liangfa.domain.ZhifaInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ZhifaInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int countByExample(ZhifaInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int deleteByExample(ZhifaInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int deleteByPrimaryKey(String infoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int insert(ZhifaInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int insertSelective(ZhifaInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	List<ZhifaInfo> selectByExampleWithBLOBs(ZhifaInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	List<ZhifaInfo> selectByExample(ZhifaInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	ZhifaInfo selectByPrimaryKey(String infoId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int updateByExampleSelective(@Param("record") ZhifaInfo record,
			@Param("example") ZhifaInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int updateByExampleWithBLOBs(@Param("record") ZhifaInfo record,
			@Param("example") ZhifaInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int updateByExample(@Param("record") ZhifaInfo record,
			@Param("example") ZhifaInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int updateByPrimaryKeySelective(ZhifaInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int updateByPrimaryKeyWithBLOBs(ZhifaInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ZHIFA_INFO
	 * @mbggenerated  Fri Jul 29 16:58:41 CST 2011
	 */
	int updateByPrimaryKey(ZhifaInfo record);
	
	List<ZhifaInfo> selectZhifaInfoIndex();
}